### ISSUE TITLE
ebib cannot reuse frame

### ISSUE THREAD

**Issue by ilupin** [joostkremers/ebib#107]
Hi, M-x ebib always creates buffers in current frame, even when ebib buffers have been displayed in other frames. Customizing `display-buffer-alist` (i.e. add `(reusable-frames . t)` for ebib buffers) has no effect. It seems ebib uses its own functions for displaying buffers. Perhaps ebib could provide an option that changes default functions?

**Comment by joostkremers** [comment]
If you run `M-x ebib`, Ebib tries to find a window displaying the index buffer. This happens in `ebib-setup-windows`. The way it works now, though, it only searches the currently selected frame. It's easy to change to make it check all frames by changing

    (get-buffer-window (ebib--buffer 'index))

in the first line of the function to

    (get-buffer-window (ebib--buffer 'index) t)

I'll make that change and push it to Github

For some reason, though, when I do this, the Emacs frame with Ebib doesn't seem to get focus on my system. As far as I understand, it should, because the doc string of `select-window` says that if the window is on another frame, that frame becomes the selected frame.

Don't know what that is, perhaps it's just my window manager.

**Comment by ilupin** [comment]
Same on my system, but I find using `select-frame-set-input-focus`(used by `pop-to-buffer`) will make sure the frame gets focus. For example,
```
  (let ((index-window (get-buffer-window (ebib--buffer 'index) t))
        (old-frame (selected-frame)))
    (if index-window
        (progn
          (select-window index-window)
          (unless (eq (window-frame) old-frame)
           (select-frame-set-input-focus (window-frame))))
```

**Comment by joostkremers** [comment]
Indeed, it seems that Emacs' idea of selected frame isn't necessarily the same as the window manager's idea of focused window. `select-window` puts input focus on the frame displaying the relevant window, but when Emacs returns to the command loop, input focus is returned to the frame that the window manager thinks is focused. So yes, we need `select-frame-set-input-focus`. Thanks for pointing out that function.

**Comment by joostkremers** [comment]
Ok, I added code to handle the use case you mention, hopefully everything works right.

The way it now works is that if you run `M-x ebib`, `ebib--setup-windows` will check if the index buffer is shown in some other frame. If it is, that frame is selected and the frame from which you restarted Ebib is stored. When you leave Ebib, the original frame is selected again.

If that frame was destroyed in the mean time, the Ebib buffers are hidden, and the frame is given to whatever buffer is returned by `other-buffer`. Unless you've set `ebib-layout` to something other than `full`, in which case what happens depends on the value of that option.

Let me know if things work as you expected, or if you still run into issues.

**Comment by ilupin** [comment]
It just works. Thanks!
