### ISSUE TITLE
Cannot add ‘inappropriate’ fields

### ISSUE THREAD

**Issue by teoric** [joostkremers/ebib#113]
[Documentation](https://joostkremers.github.io/ebib/ebib-manual.html#undefined-fields) sounds as if it were possible to add any field by pressing <kbd>a</kbd>. However, if I try to add `issuesubtitle` as a key for an article while in `BibTeX` dialect, the `re-search-forward` in `ebib-add-field` seems to fail, and a field is not added. It does work to unhide in `BibLaTeX` dialect, but only for cases where it is defined, of course, such as articles.

It would be helpful to get a clearer error message in these cases, and maybe it should be possible to add such ‘inappropriate’ fields? Otherwise the documentation should probably state that you cannot add fields that could be valid in another dialect or bibentry type that `ebib` understands.

**Comment by joostkremers** [comment]
> [Documentation](https://joostkremers.github.io/ebib/ebib-manual.html#undefined-fields) sounds as if it were possible to add any field by pressing <kbd>a</kbd>.

Actually, yes, that was my intention. 

> However, if I try to add `issuesubtitle` as a key for an article while in `BibTeX` dialect, the `re-search-forward` in `ebib-add-field` seems to fail, and a field is not added. It does work to unhide in `BibLaTeX` dialect, but only for cases where it is defined, of course, such as articles.

I can't check right now (I'm not at a computer that runs Emacs), but looking at the code I"m surprised `re-search-forward` fails, because if adding the field does not work, you should get an error message.

> It would be helpful to get a clearer error message in these cases, and maybe it should be possible to add such ‘inappropriate’ fields? Otherwise the documentation should probably state that you cannot add fields that could be valid in another dialect or bibentry type that `ebib` understands.

It was my intention that you can add any field you want, except fields that are already defined for the entry type in question. So it shouldn't matter that the field you're trying to add is defined for another entry type. And looking at the code, it seems that's what it *should* be doing. I don't understand why it doesn't.

In fact, when I think about it, it shouldn't really matter whether a field already exists or whether it's defined or not when you type `a` in the entry buffer. It would make more sense (and would be easier to implement, I think) if you could simply add any field to the entry using `a`.

I'll look into implementing that as soon as I have some time this week. That should take care of your use case.

Thanks for reporting this. I'll let you know as soon as I push any changes.

**Comment by joostkremers** [comment]
I've found the problem: it's not so much that you cannot add the field, the field is there. The problem is that it is listed as one of the hidden fields and therefore it is not listed in the entry buffer. For that reason, the search fails. If you display the hidden fields (with `H` in the index buffer), you'll notice that the field does exist.

So I need another way of fixing it. The first step will be displaying all fields that have a value, regardless of whether they are hidden or not. But that won't solve your problem, because when the field is first added, it is stored without a value, so it wouldn't be displayed, leaving you in the same predicament you're in now.

I'll need to think a bit about how I can solve this. I'll let you know when I come up with a solution.

**Comment by teoric** [comment]
Great, thank you for looking into this! I did indeed not notice that the adding succeeds, but creates a hidden field. If it is difficult to fix, it's maybe all right to just document that to avoid that.
