### ISSUE TITLE
How to handle interdependent bib files

### ISSUE THREAD

**Issue by rpgoldman** [joostkremers/ebib#119]
I have a pretty large number of bib files, including two that generally need to be loaded first, `strings.bib` and `names.bib`, which define a number of string abbreviations that are used by the other bib files.  There is also `collections.bib`, which generally needs to be loaded last, in order to make sure that `@crossref` links work properly.

Assuming I have `file1.bib`, `file2.bib`, and `file3.bib`, what's the right way to load all of these into ebib together with `strings.bib`, `name.bib`, and `collections.bib`?  I see the variable for preloaded bib files -- is that the way?

**Comment by joostkremers** [comment]
The files listed in `ebib-preload-bib-files` are opened when Ebib is started. You can use it to open all your `.bib` files automatically. Note, however, that Ebib doesn't check for `crossref`s across databases, so that feature won't actually work in your setup. I admit that it would be nice if it did, but implementing that would require a bit of thinking, because currently following a `crossref` is done in the database code (`ebib-db-get-field-value`, to be precise), which, ideally, shouldn't access any other database other than the one it's been passed as an argument.

So the best way to go about it would be to add a higher-level function that gets a field value and is able to follow a crossref across databases. But then it might be helpful for the user to be able to tell Ebib which other databases to check, so Ebib doesn't spend too much time searching.

Ebib doesn't resolve `@string` definitions. Parsebib does have the ability to do that, but Ebib doesn't make use of it (and it would actually take a bit of a rewrite in order to do so). My take is that Ebib should just show you what's in the `.bib` file without having to make you guess. Where it would be useful is in completion when entering an abbrev as a field value. That, too, only works for `@string` abbrevs defined in the `.bib` file itself, not across files.

I'd be open to implementing such cross-db lookups (no promise on the time frame, though :smile:) so if you have any particular suggestions, feel free to let me know.

**Comment by joostkremers** [comment]
> I'd be open to implementing such cross-db lookups
I've implemented this, looks like it's working fine. I'm planning to make a few more changes to better deal with interdependent `.bib` files, will let you know when they're merged.
