### ISSUE TITLE
Prohibit inserting an entry with a key that is already in the database

### ISSUE THREAD

**Issue by Knusper** [joostkremers/ebib#129]
Right now it is possible to yank an entry into a database with a key that is already present in the database. This has the strange side-effect, that the original entry gets displayed twice in the list.  Some behaviour that prevents inserting entries with identical keys would be desirable.

**Comment by joostkremers** [comment]
That's not good... Actually, in a way, it's not as bad as as it looks, but at the same time, it's worse...

It's not as bad as it looks because if you yank an entry with a key that's already in the database Ebib does the right thing: it rejects the entry and logs a warning about it. (See the `*Ebib-log*` buffer.) Or, if `ebib-uniquify-keys` is set to `t`, Ebib creates a unique key by appending `b` (or `c`, or `d`, whatever it takes). So the `.bib` file itself is ok.

What's worse, though, is that the index buffer doesn't reflect this properly. So once you yank an entry with a key that already exists, whatever is in the index buffer does not accurately show you what's in the database.

Thanks for pointing this out. I'll try and push a fix as soon as I can.

**Comment by joostkremers** [comment]
Ok, try the update. It should now work as advertised.

**Comment by Knusper** [comment]
Oh - unfortunately, I just realised that I can not update - I am still on melpa version 20180817.1024, and I never realised that many new updates have been pushed, which where not automatically upgraded... The reason is that use debian stretc, but this ships only with emacs 25.1.1 - but apparently ebib now requires 25.3 ..

**Comment by joostkremers** [comment]
Oh, that not good... That basically happened when I upgraded the Emacs version dependency from 24 to 25. I don't remember if there was any reason why I decided in 25.3 instead of 25.1, but I'll look into it. If Emacs 25.1 works as well, I'll fix the dependency. Otherwise, I could branch off a pasture branch like I did when I dropped support for Emacs 23.

**Comment by joostkremers** [comment]
From what I can tell, the main differences between Emacs 25.3 and 25.1 are bug fixes, no substantial changes to Elisp were made. I've been able to test Ebib with Emacs 25.2, and I'll try and see if I can test it with Emacs 25.1 as well. Stay tuned.

**Comment by Knusper** [comment]
Thank you so much for putting work into this.  It is greatly appreciated!

**Comment by joostkremers** [comment]
Ok, I just checked on Emacs 25.1 and Ebib at least compiles without warnings or errors. That's not a 100% guarantee that everything will work, but I suspect it will be fine.

I lowered the minimal Emacs version that Ebib depends on to 25.1, so hopefully `package.el` will now install the updates.

Do let me know if you still run into any trouble, whether it's with the fix for your original problem or with anything else that used to work but now doesn't. If it turns out there are some incompatibilities with Emacs 25.1, I'll try to fix them.

**Comment by Knusper** [comment]
So I finally got around to testing this on emacs 25.1.1. The initial behaviour in this bug is fixed. However, inserting the entry with the automatically corrected entry does now not create a timestamp automatically, i.e. the entry is inserted with no-timestamp.

**Comment by joostkremers** [comment]
Oh boy, that's not good... I'll look into this as soon as I can.

**Comment by joostkremers** [comment]
Commit 8e18834388c4ddb7233136e2e93669d1825d0b63 fixes this issue. Turns out this is a very old bug, not really related to the original issue. Thanks for reporting it.
