### ISSUE TITLE
Make default directory more flexible

### ISSUE THREAD

**Issue by pedrormjunior** [joostkremers/ebib#143]
https://github.com/joostkremers/ebib/blob/d62b5a49a1d68dab053dcf79c9e16eb29bf5f7a6/ebib.el#L980

Is there a reason to keep Ebib always on HOME directory? I've been doing `M-x cd` to another directory after opening Ebib for a while and I've found no problem.

In my case, I keep my BibTeX files under the track of Git and I would like to call Magit from Ebib (through keybindings) and go directly to the repository. However, after opening Ebib, I always need to `M-x cd` to the repository to be able to call Magit easily.

If it is not that important to make sure Ebib is always on HOME directory, let me know. Two possible alternatives would be (1) to define a variable specifying the default directory or (2) keep it on the same directory of the BibTeX file being used.

What do you think? Let me know.

**Comment by joostkremers** [comment]
I added that line about a year ago to make sure that `read-file-name` would start in `$HOME` rather than in the directory Ebib was started in (which annoyed me).

Since then I have changed the default directory for `read-file-name` to the first directory in `ebib-bib-search-dirs`, so it's probably not really helpful anymore to set `default-directory` to `~` unconditionally.

Let me try it out a bit to see if I can remove it altogether or whether I prefer to have a configurable option.

**Comment by joostkremers** [comment]
I just pushed a commit that creates a new user option `ebib-default-directory`. The default is `nil`, which means that Ebib's default directory is the directory you start Ebib in. That is the setting that you prefer, if I understand you correctly. I thought about setting the default to `$HOME` or something, but I believe having `nil` as default makes the most sense, plus it's easier to explain in the manual. :smiley:

Let me know if you run into any problems.

**Comment by pedrormjunior** [comment]
Hello @joostkremers, it is working perfectly to my needs after setting up the new `ebib-default-directory` to the same directory where my `ebib-preload-bib-files` files are. Thank you!

**Comment by joostkremers** [comment]
Great! Thanks for letting me know.
