### ISSUE TITLE
Error when adding keywords with single keywords file

### ISSUE THREAD

**Issue by Korydween** [joostkremers/ebib#146]
Hi there, 
I am having an issue with the single keyword file configuration. 

I am trying to add keywords to my DB with a single keyword file called keywords.txt
When I go on the entry and type `K a` to add a new keyword, I can type my keyword, but when pressing ENTER I get the following error: 
```
Wrong type argument: consp, nil
```
and the keyword does not appear in the field. 

If I close the database and re-open it, however, the added keyword is present. 
I am using emacs 26.3, ebib version 20191207.844, with biblatex dialect and the following configurations: 

```
 '(ebib-bibtex-dialect (quote biblatex))
 '(ebib-extra-fields
   (quote
    ((BibTeX "crossref" "annote" "abstract" "keywords" "file" "timestamp" "url" "doi")
     (biblatex "crossref" "annotation" "abstract" "keywords" "file" "timestamp"))))
 '(ebib-file-associations (quote (("pdf" . "evince") ("ps" . "gv"))))
 '(ebib-file-search-dirs (quote ("~" "~/work/literature/papers")))
 '(ebib-keywords-file "~/work/literature/keywords.txt")
 '(ebib-keywords-use-only-file t)
 '(ebib-notes-new-note-hook nil)
 '(ebib-notes-open-note-after-hook (quote (org-back-to-heading org-show-subtree)))
 '(ebib-notes-template "** TODO %T
:PROPERTIES:
%K
:END:
>|<
")
 '(ebib-notes-template-specifiers
   (quote
    ((75 . ebib-create-org-identifier)
     (84 . ebib-create-org-title-custom)
     (76 . ebib-create-org-link)
     (70 . ebib-create-org-file-link)
     (68 . ebib-create-org-doi-link)
     (85 . ebib-create-org-url-link))))
 '(ebib-notes-use-single-file "~/work/literature/literature.org")
 '(ebib-preload-bib-files (quote ("~/work/literature/master.bib")))
 '(ebib-reading-list-template-specifiers
   (quote
    ((75 . ebib-reading-list-create-org-identifier)
     (84 . ebib-create-org-title-custom)
     (77 . ebib-reading-list-todo-marker)
     (76 . ebib-create-org-link)
     (70 . ebib-create-org-file-link)
     (68 . ebib-create-org-doi-link)
     (85 . ebib-create-org-url-link))))
```
I tried with a brand new database, with only one entry created through ebib and the error appears.

**Comment by Korydween** [comment]
Nevermind, the problems seemed to be coming from my keyword file itself, that I created beforehand. When I tried again with a blank file, everything worked well. Maybe a weird invisible character somewhere. 
Sorry about the bother.

**Comment by joostkremers** [comment]
Do you still have the original keywords file, the one that you created yourself? It would still be good to figure out what caused the error.

**Comment by Korydween** [comment]
Unfortunately no. I managed to recreate the problem once by creating an empty file with the "touch" command, but after opening the file it worked properly again and I can't reproduce again, even with an empty file. So not sure if it comes from the file or something else. If I manage to reproduce the problem again, I'll put comment here.

**Comment by Korydween** [comment]
I managed to reproduce the problem. 
Here are the steps I used.
 - Ebib was open with DB opened, keyword filed entered in the configuration
 - I saved a couple of keywords
 - I realized that the keyword file I was using in the config was badly placed and named, so I moved the old config file to the new location (with `mv ~/my-old-file.txt ~/work/user/my-new-file.txt`)
 - I changed ebib configuration to take the new config file and saved my changes
 - The bug appeared
 - I closed the DB and reopened it
 - The bug is still here 
 - I quit completely ebib and restart it, the bug disappeared

So it might be a problem when the config file is somehow moved or deleted while ebib is still running.

**Comment by joostkremers** [comment]
Thanks for that detailed description. I can now reproduce the problem and it's basically what you discovered. Ebib keeps a list of keyword files (in case you use a single keywords file for all `.bib` files, this is a list of one entry), which is initialised when Ebib is started. If you change the location of the keywords file while Ebib is running, this list is not updated, so when you try to save a keyword, Ebib cannot find the file and produces an error. Restarting Ebib solves this issue, because that reinitialises the list of keywords files.

In fact, I think I'll make that the official way to deal with this problem: I'll add a warning to the option `ebib-keywords-file` that changing it requires restarting Ebib. The keywords code is complicated enough as it is, I'm not sure I could add a way to keep track of changing locations of keywords files that doesn't cause a multitude of further problems...

I will add some error checking around the code that triggers the bug, however, so that when it happens again, the user sees a more useful error message.
