### ISSUE TITLE
ebib-insert-citation: allow multiple entries

### ISSUE THREAD

**Issue by atanasj** [joostkremers/ebib#149]
It would be great if `ebib-insert-citaiton` allowed for multiple entries to be added, instead of doing this via the `index`. This seems like it would be much quicker on the fly. 

Is this possible?

**Comment by joostkremers** [comment]
It's probably possible, but not without some work, not least because it needs to be done for each of the three completion mechanisms that Ebib supports (standard completion, ivy and helm). I can't promise anything, but I will keep it in mind.

**Comment by joostkremers** [comment]
I just pushed commit ff0655f, which implements this functionality. Please test it and see how well it works.

If you use ivy or helm, it should now be possible to select multiple entries. If you use Emacs' standard completion, you need to set the option `ebib-citation-insert-multiple` to `t` before you can do so. The details are discussed in the manual.

If you run into problems (and I suspect you will, since I've only tested it a bit), I would appreciate it if you could let me know.

**Comment by atanasj** [comment]
I'm getting the following error when trying to install `ebib`: 

```emacs-lisp
Error (use-package): Failed to install ebib: https://melpa.org/packages/ebib-20200206.1637.tar: Not found
```

Not sure why... I'll try again later.

**Comment by atanasj** [comment]
I use `ivy` but cannot insert more than one citation at a time... here is my config:

```emacs-lisp
  (use-package ebib
    :config
    (setq ebib-preload-bib-files '("/Users/atanas/.pandoc/MyLib.bib")
          ebib-layout 'index-only
          ebib-file-associations '(
                                   ;; open via openwith
                                   ("pdf" . "open")
                                   ("ps" . "gv"))
          )
    :bind
    (:map markdown-mode-map
     ("M-s-b" . ebib)
     ("C-M-s-b" . ebib-insert-citation))
    ;; :hook (ebib . golden-ratio-mode)
    )
```
What am I supposed to do to insert multiple citations?

**Comment by joostkremers** [comment]
You should execute `ivy-call` (by default bound to `C-M-n`) instead of `ivy-done` (`RET`) on an entry if you want to select more entries. Then on the last entry, type `RET`.

Alternatively, you can bring up the hydra with (`C-o`), there you can mark entries with `m`, then `d` to finish selection.

The details are in the [ivy manual](https://oremacs.com/swiper/#key-bindings).

Note, BTW, that selecting multiple entries only makes sense in Markdown files with the `paren` citation command. `text` and `year` don't allow multiple keys. You'd have to modify their definitions to make that work.

**Comment by atanasj** [comment]
Okay, that works as expected, thanks for that. However, when using `ivy`, each entry asks a `Argument 1` and `Argument 2`. Is there anyway of only asking for `Argument 1` on the first citation (based on alphabetical order of authors) and then `Argument 2` at the end of the selection. 

Also, it seems as if citations are not being de-selected and sometimes the same citation is being inserted twice... Not sure what could be causing this?

**Comment by joostkremers** [comment]
> Okay, that works as expected, thanks for that. However, when using `ivy`, each entry asks a `Argument 1` and `Argument 2`. Is there anyway of only asking for `Argument 1` on the first citation (based on alphabetical order of authors) and then `Argument 2` at the end of the selection.
 
What you describe is the effect of the way the citation command is defined. The `paren` command for Markdown (which I assume you're talking about) is defined as:

    "[%(%<%A %>@%K%<, %A%>%; )]"
    
The part between `%(` and `%; )` is repeated for every selected key. Since it contains two arguments (`%A`), you are asked for arguments for each key separately. Pandoc Markdown explicitly allows that, so that's the default in Ebib. However, you can change the definition to:

    "[%<%A %>(%@%K%; )%<, %A%>]"

that is, take the two `%A` directives out of the `%(...%)` part. Then you'll only be asked for the two arguments once.

Sorting the keys in alphabetical order would be possible in principle, but it's not implemented. I prefer to keep the keys in the order that users select them, because they may have some reason to do so.

> Also, it seems as if citations are not being de-selected and sometimes the same citation is being inserted twice... Not sure what could be causing this?

If you press `C-M-m`, you actually perform an action on the candidate, which in this case is adding it to the list of keys to be cited. If you press `RET`, you do the same thing, but it additionally ends the ivy session. So if you first press `C-M-m` on a candidate and then `RET` on the same candidate, it gets added to the list of keys twice. (I could change it so that a key cannot be added twice, which would make sense in this case.)

For the same reason, you cannot deselect a candidate, because you're not really selecting one: `C-M-m` performs an action on the candidate, it doesn't select it. Ivy does have a way of selecting (and deselecting) candidates, but by default it's only available from the ivy hydra (which you can open with `C-o`). Personally, I have the following in my ivy config:

```
(use-package ivy
  :diminish ivy-mode
  :ensure t
  :bind (:map ivy-minibuffer-map
              ("C-SPC"   . ivy-mark)
              ("C-S-SPC" . ivy-unmark))
  :config
  (ivy-mode 1))
```

That way, marking and unmarking are also available in the normal ivy interface, without having to open the hydra. Ebib can handle this as well, so you may prefer it over `C-M-m`.

**Comment by joostkremers** [comment]
Note: `C-M-m` calls `ivy-call`, which performs the default action on the current candidate. `C-M-n`, which I mentioned earlier, calls `ivy-next-line-and-call`, which performs the action and then moves to the next line.

**Comment by atanasj** [comment]
Thanks for that. I didn't know about the `mark` and `unmark` options in `ivy`, that's made it really nice to use. I think only having the option to insert at the start and end of the group would be great. I use APA formatted citations primarily, so that's why I suggested that alphabetical, but I'm pretty sure `pandoc-citeproc` would take care of that. 

How hard would it be to implement only one pre and post argument?

**Comment by joostkremers** [comment]
> I use APA formatted citations primarily, so that's why I suggested that alphabetical, but I'm pretty sure `pandoc-citeproc` would take care of that.

Well, `pandoc-citeproc` *should* take care of that, I don't know if it does, though. I know that for example biblatex does take care of ordering the citations.

> How hard would it be to implement only one pre and post argument?

Like I said, you need to redefine the citation command in Ebib: `M-x customize-option RET ebib-citation-commands RET`. Details are in the manual:

http://joostkremers.github.io/ebib/ebib-manual.html#defining-citation-commands

But if you use the definition I gave above you should be good to go.

**Comment by atanasj** [comment]
Thanks. I set the variable as `"[%<%A %>(%@%K%; )%<, %A%>]"`, however it ask for a separator. When not choosing a separator or providing any other arguments the citations come out as follows: `[(%@joiner2009joiner2005joiner2005b%; )]`. Did I do something wrong?

**Comment by joostkremers** [comment]
No, I made a mistake. I misplaced a `%` sign. It should be:

    "[%<%A %>%(@%K%; )%<, %A%>]"

Hope I got it right this time...

**Comment by atanasj** [comment]
Awesome! Thanks so much, this is working great.
