### ISSUE TITLE
Can't use evince to open pdf files

### ISSUE THREAD

**Issue by juanerasmoe** [joostkremers/ebib#150]
I was trying to configure ebib to use evince as pdf reader, but it just refuses to work.
Adding this to my config file
` '(ebib-file-associations (quote (("pdf" . "evince") ("ps" . "gv"))))`
I do get a message saying "Executing 'evince /right/path/to/file.pdf', but evince doesn't launch. Executing the same line in terminal works. Also, replacing evince with firefox in the above config line opens the file in firefox.

Things I've tried:
* '(ebib-file-associations (quote (("pdf" . "evince %s") ("ps" . "gv"))))
* '(ebib-file-associations (quote (("pdf" . "evince %s &") ("ps" . "gv"))))

My config:
* Ubuntu 18.04 up to date
* Emacs version: 26.3
* Ebib version: 20200224.1517

**Comment by joostkremers** [comment]
This is weird... I have the same Emacs version and an OS based on Ubuntu 18.04 (albeit not Ubuntu itself) and I can use Evince just fine, so it's difficult for me to know what's wrong... The fact that you see the message "Executing 'evince /right/path/to/file.pdf'" suggests that Emacs finds the `evince` executable, because if it didn't, you'd see an error message instead.

A few things you can try to hopefully get some more information:

- Check the `*Messages*` buffer after trying to open a file with Evince from Ebib (press `C-h e` to see it).

- Start Emacs from the command line and see if there are any error messages there when you try to call Evince from Ebib.

- Try calling Evince from Eshell (`M-x eshell`).

- Open an IELM buffer (`M-x ielm`) and enter the following expression:

        (start-process "my_process" "*scratch*" "evince" "full/path/to/your.pdf")

  Then check the `*scratch*` buffer to see if there's anything there.

**Comment by juanerasmoe** [comment]
> Check the *Messages* buffer after trying to open a file with Evince from Ebib (press C-h e to see it).
All it says is `evince /home/right/path/document.pdf`

> Start Emacs from the command line and see if there are any error messages there when you try to call Evince from Ebib.
No messages

> Try calling Evince from Eshell (M-x eshell).
This doesn't work. Returns a hangup message (?)

> Open an IELM buffer (M-x ielm) and enter the following expression:
Another hangup message

**Comment by joostkremers** [comment]
Not sure exactly what you mean with "hangup message", but it suggests that there is something weird going on with either your Emacs or your Evince. It doesn't look like it has anything to do with Ebib. Perhaps you can ask on [help-gnu-emacs](https://lists.gnu.org/mailman/listinfo/help-gnu-emacs).

**Comment by juanerasmoe** [comment]
I agree. Seems like a weird issue with my emacs setup
