### ISSUE TITLE
multiple .bib files: key not found

### ISSUE THREAD

**Issue by atanasj** [joostkremers/ebib#154]
I am using multiple `.bib` files, however `ebib` does not seem to find it. I have the following line in my `use-package` config: 

```elisp
(setq ebib-preload-bib-files '("/Users/atanas/.pandoc/MyLib.bib" "/Users/atanas/path/to/second/file.bib"))
```
Any idea what I'm doing wrong?

**Comment by joostkremers** [comment]
It's difficult to say without a more detailed description. Do you mean the files aren't found? Or one particular key?

**Comment by atanasj** [comment]
It seems the files are not found. The first file is found, however the second is not. I can confirm that the keys are in the second `.bib`, however for some reason `ebib` appears to not be loading the file… Is there any other info you need that could help resolve this issue?

**Comment by joostkremers** [comment]
Ebib writes some info to a log buffer: type `l` (lowercase L) after starting Ebib to see the log. It may say something helpful.

Is the file then even loaded? Can you view it in Ebib? If you can, is the relevant entry in the database?

Other than that, I can only suggest to carefully check the file name and the key...

**Comment by atanasj** [comment]
The log buffer says: 

```elisp
08 May 2020, 00:32:18: Opening file /Users/atanas/CloudDrive - Org Ltd/Org/GPH.bib
63 entries, 0 @Strings and no @Preamble found in file.
Using general keyword list.
```

It is a similar message to my primary file and has this load without issues. The file name and keys are all in there. The entries are not able to be viewed in Ebib.

Any other thoughts on what could be wrong?

**Comment by joostkremers** [comment]
> Any other thoughts on what could be wrong?

Nope. I'd really have to see the entries or preferably the whole bib file. Would it be possible to paste some of the problematic entries here, or send me the bib file via e-mail?

**Comment by atanasj** [comment]
Yes, happy to send you the bib file. What's the best contact?

**Comment by joostkremers** [comment]
I don't have any trouble viewing the entries in Ebib...

You do realise that Ebib creates a separate index buffer for each bib file you open? You can switch to the next/previous bib file with the left and right cursor keys, or use `1`, `2`, etc. to switch to the first, second, etc. database.

I've long had vague plans to create a unified view that displays all bib files in a single index buffer, but I never got round to implementing it.

If you use `j` to jump to an entry, you can select an entry in any database, however.

**Comment by atanasj** [comment]
Oh… Sorry, I missed that. How do I select an alternative bib file when selecting `ebib-insert-citation`? Seems to default to the first bib file and cannot see how to select the second. 

> I've long had vague plans to create a unified view that displays all bib files in a single index buffer, but I never got round to implementing it.

Would a unified view resolve this issue?

**Comment by joostkremers** [comment]
> Oh… Sorry, I missed that. How do I select an alternative bib file when selecting `ebib-insert-citation`? Seems to default to the first bib file and cannot see how to select the second.

If your text is a LaTeX file, Ebib looks for `\addbibresource` commands or a \bibliography command and reads the databases from them. If you use `pandoc-mode`, Ebib uses the `--bibliography` setting for your file. Otherwise it just uses the bib file that you are viewing when you lower Ebib. I realise now that it probably makes more sense if Ebib use all open bib files in that case, though. I'll fix that tomorrow.

The manual mentions that you can also set the variable `ebib-local-bibtex-filenames` in a file-local variable block, but that functionality currently doesn't work. I should fix that, too.

> > I've long had vague plans to create a unified view that displays all bib files in a single index buffer, but I never got round to implementing it.
> 
> Would a unified view resolve this issue?

Yes, probably. I'm just not sure how feasible that is with the current code, though, because Ebib is built around the notion that there is a single "current" database. (There are almost 400 uses of the variable `ebib--cur-db` in the code, for example...)

Though I guess it should be possible to replace that variable with a function that returns the correct database...

**Comment by joostkremers** [comment]
> I realise now that it probably makes more sense if Ebib use all open bib files in that case, though. I'll fix that tomorrow.

Pushed a fix just now.

**Comment by atanasj** [comment]
Thanks @joostkremers, that works well! 👍 😄
