### ISSUE TITLE
Misleading prompt message when editing author field

### ISSUE THREAD

**Issue by rafreeman** [joostkremers/ebib#155]
When I edit the author field, I get a prompt that says "Add a new author (ENTER to finish):" but when I actually hit ENTER it just adds the top author on the completion list and then goes back to the prompt.  It turns out that I have to hit BACKSPACE to finish.  Is this because I am using the ivy completion package?

**Comment by joostkremers** [comment]
I'm surprised that hitting `BACKSPACE` works, but yes, it's because you use Ivy. With standard Emacs completion, hitting `RETURN` works.

I use Ivy myself and I use `ivy-immediate-done` to finish. I've bound this to `C-RET`, but the default key binding for this command is `C-M-j`. I guess `BACKSPACE` is easier. :smiley:

It would be nice to show the actual key the user needs to hit in order to finish entering author names. Should be doable once I figure out how helm does it...

**Comment by joostkremers** [comment]
> It would be nice to show the actual key the user needs to hit in order to finish entering author names. Should be doable once I figure out how helm does it...

Ok, I just pushed a fix for this. The prompt should now give you a key binding that really works, `C-M-j` in your case (unless you rebound `ivy-immediate-done` to something else, then that key binding should be shown).

**Comment by rafreeman** [comment]
The fix works, thanks!
