### ISSUE TITLE
ebib conflicts with (save-some-buffers)

### ISSUE THREAD

**Issue by lockywolf** [joostkremers/ebib#157]
I am finding it a little hard to reproduce, but in certain configurations the following stack trace appears (I am saving everything on timeout):

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  ebib--update-entry-buffer()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
```
Perhaps ebib buffer needs to be somehow marked as not needing save? Or something like that?

And this error keeps appearing even after quitting ebib. For some reason `ebib--update-entry-buffer()` remains in the `after-save-hook`.

**Comment by joostkremers** [comment]
Hmmm... `after-save-hook` is only set buffer-locally in buffers containing notes, because the first lines  of a note are displayed in the entry buffer, so if the contents change, the entry buffer should be updated. It seems to make most sense if this is done after saving the note, that's why I use `after-save-hook`.

Unfortunately, the backtrace isn't very helpful, because it doesn't say where exactly in `ebib--update-entry-buffer` the error occurs. Perhaps it would help if you could run Ebib with this function not byte-compiled?

It might also help if you could show me your Ebib configuration.

**Comment by lockywolf** [comment]
Well, what you're doing seems correct, but won't work if there is no buffer to update. 

Perhaps the hook could self-destroy if the notes buffer is still open while there is no entry buffers?

**Comment by joostkremers** [comment]
Removing `ebib--update-entry-buffer` from `after-save-hook` doesn't seem useful, because the entry buffer may reappear. It would be better to have a function that first checks whether the entry buffer needs updating

**Comment by joostkremers** [comment]
I have found a way to reproduce the bug. It basically happens when you save a note when Ebib isn't running. If you quit Ebib with `q`, the entry buffer is killed, so when `after-save-hook` tries to update it, it of course fails. Reopening Ebib recreates the entry buffer, at which point updating it from `after-save-hook` works again.

I changed the hook function so that it first checks if the entry buffer exists at all. That should fix the issue you're seeing.

On a side note, if you haven't already, it's probably best to get into the habit of using `z` to leave Ebib. That way its buffers stay live and returning to Ebib is quicker. (Well, in my case, at least. My main `.bib` file is rather large and it's slow to load...)

Thanks for reporting this bug.
