### ISSUE TITLE
request: command line arguments for "ebib-file-associations"

### ISSUE THREAD

**Issue by ryofurue** [joostkremers/ebib#163]
I'm new to ebib and finding the capability of opening PDF files very useful.

I may be missing something (and that's quite possible!), but I thought it would be nice if you could give command line arguments to the viewer command, as
````
(setq ebib-file-associations
      '(("pdf" . "open -a Skim"))) ;-- doesn' work.
````
With the above, ebib tries to invoke a command named "open -a Skim", which doesn't exist.

Currently, I'm stuck with `("pdf" . "/Applications/Skim.app/Contents/MacOS/Skim")`.

As a workaround,  I could create a wrapper shell script that encapsulates "open -a Skim".

I'm using macOS 10.15.5 and emacs 26.3 and ebib that is installed from the standard place (ELPA or MELPA).

**Comment by joostkremers** [comment]
You're not missing anything, right now it's indeed not possible to add command line arguments to a viewer. I agree it would be a nice thing to have, though, so I'll look into it when I find some time. I can't make any promises as to when, though.

**Comment by joostkremers** [comment]
Well, lo and behold. It **is** possible, I just completely forgot about it...

You need to add `%s` to the command string, which will then be replaced with the file name. So in your case, you'd have to specify the command string as:

    open -a Skim %s

If there's a `%s` in the command string, Ebib assumes you're specifying a command with arguments and should do the right thing.

I suspect there may be problems if the full file path has spaces in it, so if that's the case in your setup it may still not work, but that's a bug I intend to  fix.

This isn't documented in the manual, I noticed, so that should be fixed as well. (It's only documented in the documentation string of `ebib-file-associations`.)

**Comment by ryofurue** [comment]
> If there's a %s in the command string, Ebib assumes you're specifying a command with arguments and should do the right thing.

Aha!  Thank you for your help.

Is that an API provided by emacs?  I can imagine that many packages need this functionality.

> I suspect there may be problems if the full file path has spaces in it,

What about
````
("pdf" . "open -a Skim \"%s\"")
````
?  Although I haven't tested the above code with a path including blanks, at least it works.

> (It's only documented in the documentation string of ebib-file-associations.)

I missed that.  Thanks.

**Comment by joostkremers** [comment]
> Is that an API provided by emacs? I can imagine that many packages need this functionality.

No, that's the way Ebib implements it. Obviously, Emacs can call external programs with arguments, but it does it in a different way. I chose this way to implement it because it's easier to customise.
 
> What about
> 
> ```
> ("pdf" . "open -a Skim \"%s\"")
> ```

Yes, that will work, but I do think it should be something Ebib should check for.

> > (It's only documented in the documentation string of ebib-file-associations.)
> 
> I missed that. Thanks.

Well, I don't expect users to check documentation strings, so it really should be in the manual...

**Comment by joostkremers** [comment]
I improved the code a bit so that Ebib now handles spaces in file names properly. There's no need to add double quotes around the `%s` in `ebib-file-associations`: Ebib takes care of them.

I also added a remark about this in the manual.
