### ISSUE TITLE
default optional fields

### ISSUE THREAD

**Issue by ryofurue** [joostkremers/ebib#164]
When you create a new entry ("a") and change its type to, say, "Book", you are given default fields for the "Book" type.  But then I've noticed that the default list of optional fields is different from what I'm familiar with:

    https://en.wikipedia.org/wiki/BibTeX

For example, the default list for the Book type on ebib doesn't include "edition".  I don't know how authoritative the above reference (Wikipedia) is, but I think at least the default list the native bibtex mode of emacs provides agrees with the above convention.

So, I was wondering if this might/should be fixed, or if there is a way for the user to change the default optional fields for each type.

**Comment by joostkremers** [comment]
For `biblatex`, the authoritative list is in the manual. If you look there, you'll notice that the list of optional fields for the `Book` type (and indeed for many other types) is quite long. For this reason, I have chosen not to show all optional fields in the entry buffer. Most of those fields will rarely, if ever, have a value and displaying them all means they won't fit on a single screen anymore. 

Ebib uses the entry types and fields defined by `bibtex-mode`, so it does know about those fields. It just decides to hide some of them. But you make them all visible by typing `H` in the index buffer. If you do that, you'll see the `edition` field appear for the `Book` type.

The option `ebib-hidden-fields` controls which fields Ebib hides by default. If you prefer to have the `edition` field visible all the time, you can simply remove it from this list (`M-x customize-option RET ebib-hidden-fields RET`) and then it will always be shown.

Even if the field is hidden, though, you can still use it: if you type `a` in the *entry* buffer, you can add a field to the current entry. Type the field name and a value for it, and then the field will appear in the entry buffer.

Note that hidden fields are only hidden if they don't have a value. If a field that is normally hidden has a value, it *will* be shown for that particular entry.

**Comment by ryofurue** [comment]
First of all, thank you so much for the detailed, comprehensive explanation! I fully understand the situation.  I didn't know that ebib's list is based on biblatex or that biblatex's list is different from what the classical conventions show.

> For this reason, I have chosen not to show all optional fields in the entry buffer. 

I see. Then, I thought it would be nice if which optional fields are shown by default depended on the type according the old convention like https://en.wikipedia.org/wiki/BibTeX .  (If I understand correctly,  `ebib-hidden-fields` uniformly applies to all entry types.)

Explanation: I have to use the old-fashioned bibtex with old-fasioned bst files.  For personal use, I use biblatex, but all publishers I deal with use rather old bst files.  I don't think I'm alone because those publishers are the main ones in my field (geosciences).

That means that I have to stick to conventions similar to https://en.wikipedia.org/wiki/BibTeX , the only exception being that url and doi are universally available.  For this reason, I *have* to know which fields are available for each type according to the classical convention.  If some fields aren't available for the type, I have either to incorporate the information in another field or to use another type.  For example, if the "edition" field isn't available for the type, I would have to incorporate the information perhaps in the title "A Guide to Home Cooking, 2nd ed."

When I was using emac's built-in bibtex mode, I was able to rely on the default fields that the bibtex mode inserts (plus url and doi).  On ebib, I have to open https://en.wikipedia.org/wiki/BibTeX each time I need to decide which fields are available.

Off-topic: It's frustrating that our publishers are so backwards.  Not only there is no sign that they will switch to biblatex, but also the development their LaTeX and BibTeX styles has almost stalled after the initial rapid development during the 2000s.

**Comment by joostkremers** [comment]
First of all, thank you so much for the detailed, comprehensive explanation! I
fully understand the situation. I didn't know that ebib's list is based on
biblatex or that biblatex's list is different from what the classical
conventions show.

> For this reason, I have chosen not to show all optional fields in the entry
> buffer.

I see. Then, I thought it would be nice if which optional fields are shown by
default depended on the type according the old convention like
https://en.wikipedia.org/wiki/BibTeX . (If I understand correctly,
`ebib-hidden-fields` uniformly applies to all entry types.)

Explanation: I have to use the old-fashioned bibtex with old-fasioned bst files.
For personal use, I use biblatex, but all publishers I deal with use rather old
bst files. I don't think I'm alone because those publishers are the main ones in
my field (geosciences).

That means that I have to stick to conventions similar to
https://en.wikipedia.org/wiki/BibTeX , the only exception being that url and doi
are universally available. For this reason, I *have* to know which fields are
available for each type according to the classical convention. If some fields
aren't available for the type, I have either to incorporate the information in
another field or to use another type. For example, if the "edition" field isn't
available for the type, I would have to incorporate the information perhaps in
the title "A Guide to Home Cooking, 2nd ed."

When I was using emac's built-in bibtex mode, I was able to rely on the default
fields that the bibtex mode inserts (plus url and doi). On ebib, I have to open
https://en.wikipedia.org/wiki/BibTeX each time I need to decide which fields are
available.

Off-topic: It's frustrating that our publishers are so backwards. Not only there
is no sign that they will switch to biblatex, but also the development their
LaTeX and BibTeX styles has almost stalled after the initial rapid development
during the 2000s.

**Comment by joostkremers** [comment]
My apologies for what looks like me usurping your comment... I wanted to quote your comment, but before I had written anything, I accidentally posted my comment, essentially reposting yours verbatim. Then when I tried to delete my reposting, I accidentally deleted your original post.

So, for future reference, the quoted text below is actually from @ryofurue. Unquoted text is from me (@joostkremers).

> I see. Then, I thought it would be nice if which optional fields are shown by
> default depended on the type according the old convention like
> https://en.wikipedia.org/wiki/BibTeX . (If I understand correctly,
> `ebib-hidden-fields` uniformly applies to all entry types.)

Yes, `ebib-hidden-fields` applies to all entry types, both BibTeX and biblatex.
 
> That means that I have to stick to conventions similar to
> https://en.wikipedia.org/wiki/BibTeX , the only exception being that url and doi
> are universally available. For this reason, I _have_ to know which fields are
> available for each type according to the classical convention.

That's actually a bit problematic, because which fields are meaningful in a BibTeX entry isn't fixed. BibTeX originally didn't know about `url` and `doi`, but like you say, they are nowadays generally available. So what fields you can use generally depends on the style files and the LaTeX package (`amsref`, `natbib`...) you use (or your publisher uses). 

I think the best way to deal with your situation is to explicitly mark the relevant `.bib` files as BibTeX files. In Ebib, you can do this with `M-x ebib-set-dialect` or in the menu "Ebib | Options | BibTeX Dialect". The dialect will get stored in a Local Variable block in the `.bib` file (which you can of course also add manually):

```
@Comment{
    Local Variables:
    bibtex-dialect: BibTeX
    End:
}
```

Ebib will then show you the entry and field definitions for BibTeX instead of biblatex for that particular file. Entry types that do not exist in BibTeX then appear in red and fields that are not defined appear below all other fields in the entry buffer.

You may still need to edit `ebib-hidden-fields` (remove `edition` for example), and perhaps `ebib-extra-fields`, but then it should mostly work.

I agree it could make sense to make the set of hidden fields dependent on the dialect (BibTeX vs. biblatex). In fact, the number of fields defined for BibTeX is relatively small, so there's probably no need to hide any fields by default. I'll see if I can implement that.

> Off-topic: It's frustrating that our publishers are so backwards. Not only there
> is no sign that they will switch to biblatex, but also the development their
> LaTeX and BibTeX styles has almost stalled after the initial rapid development
> during the 2000s.

Honestly, I think it's horrible that BibTeX is still around in this day and age. The BibTeX program itself has, as far as I can tell, not been updated since 1988 and will often do the wrong thing if you pass it anything but pure ASCII. It would be good if the major TeX distributions would start to deprecate it (just like they should start deprecating pdflatex... :smile: )

**Comment by ryofurue** [comment]
Thank you again for your message!  I think that solves my problem (see below).

> I think the best way to deal with your situation is to explicitly mark the relevant .bib files as BibTeX files. In Ebib, you can do this with M-x `ebib-set-dialect`

I've looked at the variable and it's already set to `BibTeX`:

    ebib-bibtex-dialect is a variable defined in ‘ebib-utils.el’.
    Its value is ‘BibTeX’

(from `M-x describe-variable` on emacs).

> You may still need to edit `ebib-hidden-fields` (remove `edition` for example)

Yes!  So, all I needed was

    (setq ebib-hidden-fields
            (remove "chapter"
                    (remove "edition"
                            (remove "month" ebib-hidden-fields))))

in my `init.el` .  (For more systematic ways to delete multiple items from a list, see https://emacs.stackexchange.com/questions/55255/remove-multiple-elements-from-a-list .)  Then, the default visible list of fields (mostly) agrees with the conventional BibTeX.

Because `doi` and `url` are already included as extra fields, the above customization is all I (and other people who need to stick to the classical BibTeX way) need.

> Honestly, I think it's horrible that BibTeX is still around in this day and age

Although I fully agree, I don't see how this situation would change.  Publishers lack incentive to invest in updating their systems. Even Elsevier's LaTeX style file has a long-standing, easy-to-fix bug, which I repeatedly pointed out (with pointers to how to fix it) and they repeatedly acknowledged but haven't fixed, for more than ten years.  They aren't interested in fixing this little bug.  That strongly suggests that they will never attempt to migrate to `biblatex` in the foreseeable future.  I hope I'm wrong.

> deprecating pdflatex

Do you mean we should all have migrated to `lualatex` by now?  I guess that's because there is no mechanism to deprecate anything in the present TeX distributions like texlive.  Benefits of luatex isn't obvious to end users.  The only way I can see would be: Change the names of commands from "pdflatex" to, say,  "old-pdflatex" . . . to force end users to switch.
