### ISSUE TITLE
Request: Copy formated citation / reference

### ISSUE THREAD

**Issue by baracunatana** [joostkremers/ebib#165]
While it is possible to copy an entry in bibtex/biblatex format, there isn't a way to copy the formatted citation for a bibtex entry.  It'll be a nice addition to an already amazing package.

**Comment by joostkremers** [comment]
Hi, sorry for the late reply. I'm not sure what you mean by "formatted citation": is it what you'd write in a text (e.g., "Chomsky (1995)"), or what you'd find in the list of references at the end of a paper (e.g., "Chomsky, Noam (1995). _The Minimalist Program_. Cambridge, MA: The MIT Press")?

Both aren't easily doable (you'd basically have to reimplement biblatex/biber in Elisp :smiley: ) but the first one can be approximated. There is in fact already a function for this and a defcustom (`ebib-citation-description-function`) and it should be fairly easy to write a command that calls this function and pushes the result to the kill ring.

**Comment by oatmealm** [comment]
I never thought about it as a requirement, since pandoc does all the work in referencing the bibliography in my case, but come to think of it, it's useful to have. Ie copying a reference to paste in discussion or email etc...

**Comment by juanerasmoe** [comment]
@joostkremers I'm talking more about the second option and my use case is exactly waht @oatmealm describres. I'm using ebib as a jabref replacement and sometimes need to copy a formatted citation in a word document or email. I'm currently doing it with org-ref (see https://github.com/jkitchin/org-ref/issues/641), but I think it would be a good addition to ebib.

**Comment by goderich** [comment]
I'd be interested in that as well, and willing to help with the implementation.

There is the question of formatting. Asking for different formats might be a bit too much, but on the other hand that could be a customisable variable with sane defaults. The function would have to grab relevant fields for different entries, format them, then output a string (paste it to clipboard?).

Might take a bit of elbow grease to do all types of documents, but starting with the most common ones (journal article, book) and slowly expanding from there might make sense.

**Comment by joostkremers** [comment]
@goderich Yes, that would be the way to go. Since org-ref apparently does something like this, it might be useful to check how it's done there. Perhaps there's some generic code that can be reused. (Though I wouldn't want to make org-ref a dependency of Ebib, of course.)

The customisable option would be an alist with entry types mapping to format strings. The format strings could use custom `%` specifiers, or field names in some special formatting. The former would have the advantage that Emacs has built-in support for them (the function `format-spec` handles custom format specifiers), the latter would be more user-friendly.

Such a format string could look like this, for example:

    "{Author|Editor} ({Year}). \"{Title}\". {Publisher}."

That would work for a "Book" or "Collection" type. Field names in braces would then simply be replaced with their contents. A pipe bar would indicate "or", so that in this example, if the "Author" field is empty, the "Editor" field would be used instead.

I've never seen braces used in an actual list of references, but it would be easy to allow using `{{` for a single opening brace and `}}` for a single closing brace.

Fields that are empty would be left out completely. To make it really nice, it would be possible to allow punctuation inside braces, which would also be left out if the field is empty, so something like:

    "{Author|Editor} ({Year}). \"{Title}\". {Publisher}. {Doi.}"

wouldn't produce an additional full stop if there is no "Doi" field in an entry.

And of course it should be possible to do things like:

    "{Author|Editor} ({Year}). \"{Title}\". {Publisher}. {Doi|Url.}"

What I wouldn't do is parsing the field contents, e.g., to abbreviate author names, things like that. Field contents would simply be copied as is.

The same system could be used to create in-text citations of the form `"Author (Year)"`. The format strings would be different (perhaps a single format string would suffice), but the rest would be the same.

**Comment by joostkremers** [comment]
I just pushed a commit, 627a99f57efe0a7dc0d8647289e42c1dbfd11e4d, that adds support for this, and also for copying the citation key, as requested in issue #175. There are four new commands, all starting with (capital) `C`. The templates work basically in the way discussed here (except that `{{` / `}}` aren't supported; I'll add that if anyone requests it).

Details are [in the manual](http://joostkremers.github.io/ebib/ebib-manual.html#copying-entries-to-the-kill-ring-and-system-clipboard).

So far, only the `Book`, `Article`, `Collection` and `InCollection` types are supported, but I'll add the other types when I find some time.

Let me know if there are any problems or remaining issues.

**Comment by oatmealm** [comment]
@joostkremers just updated and tested the new release. As far as I'm concerend this is a very helpful enhancment and the keybindings chosen make it very easy to use. :+1:

**Comment by baracunatana** [comment]
Brilliant. Works great. Also, the option to include a . only if a field is present makes it really flexible.
 
Thanks.

**Comment by joostkremers** [comment]
Just FYI: I added a few more entry types. I'm not really sure what to do with the remaining ones, since I don't use them and I'm not sure what a reference would look like. I'd be happy to accept suggestions for them, though.
