### ISSUE TITLE
Nonstandard field "shorttitle"

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#177]
As far as I understand "shorttile" is not a standard bibtex or biblatex field...? It's not listed in ebib's hidden fields...can I update `ebib--hide-hidden-fields` manually, or is there a better way to do it? 

Note: It seems to be supported by zotero, and is correctly exported by zotero (via Better BiBLaTex, and correctly consumed and used by pandoc, using this bib file.

**Comment by joostkremers** [comment]
`shorttitle` is supported by biblatex (it's in the documentation), I don't know about BibTeX. Ebib uses the type and field definitions in `bibtex.el`, so apparently it's not there. (Which makes sense, because it's only used in some citation styles, and it's not a required or optional field for any entry type).

The way to deal with this is to customize the option `ebib-extra-fields` and add `shorttitle` to it. Then it will appear in the third block of fields in the entry buffer.

There's no need to do anything with `ebib-hidden-fields`, because `shorttitle` isn't in there. As soon as `shorttitle` is defined in some way, it will be visible.

Alternatively, you could customize `bibtex-BibTeX-entry-alist` and/or `bibtex-biblatex-entry-alist`, but you'd have to add `shorttitle` to every entry you want it to appear in.

Note that you don't *have* to define a field in order to add it to an entry. You can type `a` in the entry buffer to add any field to the current entry. But if you use `shorttitle` a lot, it's more practical to define it, of course.

**Comment by oatmealm** [comment]
Oh I see. I thought it was strange I wasn't seeing it. I used the 'a' shortcut to add the field indeed like you described, but indeed I'd like it to be always present. Thanks. Closing.
