### ISSUE TITLE
Date field beginning with a space cannot be parsed

### ISSUE THREAD

**Issue by goderich** [joostkremers/ebib#180]
Hello Dr Kremers!

In my biblatex database, I have entries with both `year` and `date` fields. Most of my database has whitespaces inside the curly brackets, like so:

```year = { 2000 },```

I noticed that with `year` fields, they get parsed just fine, spaces included. The `date` fields though cannot be parsed if they begin with a space.

I've tracked this bug to the `ebib-get-year-for-display` function in `ebib-utils.el`. I see that the parsing is done through regexes. I suggest using in-built functions instead of trying to match all possibilities manually. I've rewritten the function in on my computer using `parse-time-string` and friends, and I'd be glad to open a PR if you're interested in trying it out. It parses both `year` and `date` just fine, and strips whitespace in the process.

PS. As an aside, maybe `ebib-get-field-value` should strip whitespace from both ends of the value? That might break some things though.

**Comment by joostkremers** [comment]
In my biblatex database, I have entries with both `year` and `date` fields. Most
of my database has whitespaces inside the curly brackets, like so:

```year = { 2000 },```

I noticed that with `year` fields, they get parsed just fine, spaces included.
The `date` fields though cannot be parsed if they begin with a space.

I've tracked this bug to the `ebib-get-year-for-display` function in
`ebib-utils.el`. I see that the parsing is done through regexes. I suggest using
in-built functions instead of trying to match all possibilities manually. I've
rewritten the function in on my computer using `parse-time-string` and friends,
and I'd be glad to open a PR if you're interested in trying it out. It parses
both `year` and `date` just fine, and strips whitespace in the process.

PS. As an aside, maybe `ebib-get-field-value` should strip whitespace from both
ends of the value? That might break some things though.

**Comment by joostkremers** [comment]
> I've rewritten the function in on my computer using `parse-time-string` and friends, and I'd be glad to open a PR if you're interested in trying it out. It parses both `year` and `date` just fine, and strips whitespace in the process.

It never occurred to me to look for built-in functions (even though I was actually aware of `parse-time-string`...)

A quick check suggests that things aren't so easy, though. There is `iso8601-parse`, which would be needed to parse the date field properly, and you'd first to check if the contents of the date field is a date range, which biblatex explicitly allows.

And, to make things interesting, `iso8601-parse` also balks at a string that starts with a space: :smile:
 
```
Elisp> (iso8601-parse "2002-01")
(nil nil nil nil 1 2002 nil nil nil)

Elisp> (iso8601-parse " 2002-01")
*** Eval error ***  Wrong type argument
```

> PS. As an aside, maybe `ebib-get-field-value` should strip whitespace from both ends of the value? That might break some things though.

I'm careful not to remove any whitespace because adding a leading or trailing space is the only way to add explicit braces around a field value. If Ebib reads:

```
    title = {{Some Title}}
```

it converts it to `"Some Title"`, while

```
    title = { {Some Title}}
````

is kept as `" {Some Title}"`, which is useful if you want bib(la)tex to use the title literally, without changing case or anything. 

I admit that's not pretty, but until I come up with a fix for it, leading and trailing spaces cannot be removed.

`ebib--get-field-value-for-display` should probably trim whitespace, though.

**Comment by goderich** [comment]
This depends on how thoroughly you want to parse the dates in Ebib. `parse-time-string` still parses the first year in a range, which is what Ebib is doing right now, but it also solves the whitespace issue. I don't know why I've accumulated so many whitespaces in my biblatex file, or if other people have them too, so I can't say if it's a common issue.

I daresay date ranges are pretty uncommon and using just the first date should be fine in most cases, since we're only talking about what shows up in the ebib index and search after all. Parsing the whole range would require calling `iso8601-parse-interval` specifically (as far as I understand it), and yes, like you mentioned, it's also not resistant to whitespace.

The one thing that `parse-time-string` struggles with is ISO8601 times such as "2004-04-05T14:34:00", but surely this is a rare enough occurrence to be ignored for now?

**Comment by joostkremers** [comment]
> This depends on how thoroughly you want to parse the dates in Ebib. 

Not very thoroughly. I just want to extract the year, and if it's a date range, the first year.

>`parse-time-string` still parses the first year in a range, which is what Ebib is doing right now, but it also solves the whitespace issue.

But I get:

```
Elisp> (decoded-time-year (parse-time-string "2002-01"))
nil
```

Not the expected `2002`. `iso8601-parse` handles it correctly:

```
Elisp> (decoded-time-year (iso8601-parse "2002-01"))
2002 (#o3722, #x7d2)
```

`parse-time-string` does handle "2002-01-01" correctly, but "2002-01" is the canonical way to specify "January 2002" in biblatex, so it should be supported.

> I don't know why I've accumulated so many whitespaces in my biblatex file, or if other people have them too, so I can't say if it's a common issue.

It's probably the way the some other utilities write their bibtex files. I make a point of not changing the field contents unless the user makes an edit, but trimming whitespace would normally be safe. Once I solve the other issue, of course. :smile: 
 
> I daresay date ranges are pretty uncommon and using just the first date should be fine in most cases, since we're only talking about what shows up in the ebib index and search after all.

Yes, that's basically what Ebib does now, so that's fine.

> Parsing the whole range would require calling `iso8601-parse-interval` specifically (as far as I understand it), 

Yes. Ebib would first need to check if the date is a range and use `iso8601-parse-interval` if it is.

> and yes, like you mentioned, it's also not resistant to whitespace.

If handling whitespace is the only real issue with the current code, that could easily be handled by adjusting the regexp a bit.

> The one thing that `parse-time-string` struggles with is ISO8601 times such as "2004-04-05T14:34:00", but surely this is a rare enough occurrence to be ignored for now?

Unfortunately, it's not the only thing `parse-time-string` can't handle. While a full date+time specification is probably rare to non-existent, I suspect a month specification such as "2002-01" is more common.

**Comment by goderich** [comment]
>parse-time-string does handle "2002-01-01" correctly, but "2002-01" is the canonical way to specify "January 2002" in biblatex, so it should be supported.

That's a very good point. I hadn't tested for YYYY-MM, and I absolutely agree with you.

Would you prefer to simply adjust the regex in the `ebib-get-year-for-display` function, then? Seeing as it should do the job of extracting the digits of the year (or first year in a range) well enough, there doesn't seem to be much call for `iso8601-parse`.

**Comment by joostkremers** [comment]
> Would you prefer to simply adjust the regex in the `ebib-get-year-for-display` function, then?

Yes, this is what I decided to do. The format allowed in the "Date" field in biblatex is pretty well defined in its manual, so I'm confident enough that a regexp will do here. I just pushed a fix that allows whitespace at the front of the date field, which hopefully fixes your issue.

Thanks for reporting and discussing this issue.

**Comment by goderich** [comment]
Thank you for responding and fixing the issue so quickly, and for the amazing tool that is Ebib! I'm sorry I couldn't be of more help in this.
