### ISSUE TITLE
`define-obsolete*` take three argument in (git) emacs

### ISSUE THREAD

**Issue by vp1981** [joostkremers/ebib#191]
Hello,
one of recent changes in emacs (git branch master) is to make `define-obsolete*` functions to have three mandatory arguments but `ebib-notes.el` uses only two (in `define-obsolete-variable-alias`) so emacs (from git repository) couldn't (byte-)compile `ebib`.

I prepared small (but of course not sufficient) patch that allow me to (byte-)compile `ebib`:
```
diff --git a/ebib-notes.el b/ebib-notes.el
index 6244cf8..248a1f5 100644
--- a/ebib-notes.el
+++ b/ebib-notes.el
@@ -43,7 +43,7 @@
 
 (defgroup ebib-notes nil "Settings for notes files." :group 'ebib)
 
-(define-obsolete-variable-alias 'ebib-notes-use-single-file 'ebib-notes-file)
+(define-obsolete-variable-alias 'ebib-notes-use-single-file 'ebib-notes-file "Ebib 2.23")
 
 (defcustom ebib-notes-file nil
   "Name of the notes file.
@@ -54,7 +54,7 @@ one file per note, provided `ebib-notes-directory' is set."
   :type '(choice (const :tag "Use multiple notes files" nil)
                  (file :tag "Notes File")))
 
-(define-obsolete-variable-alias 'ebib-notes-file-symbol 'ebib-notes-symbol)
+(define-obsolete-variable-alias 'ebib-notes-file-symbol 'ebib-notes-symbol "Ebib 2.23")
 
 (defcustom ebib-notes-symbol "N"
   "Symbol used to indicate the presence of a note for the current entry.
-- 
```

About "Ebib 2.23": using git(hub) I traced that `define-obsolete*` was introduced around when 2.23 version was release so I took that version as reference.

P.S. This change was done in commit 32c6732d16385f242b1109517f25e9aefd6caa5c but Emacs Lisp documentation still shows that `define-obsolete-variables-alias` has only two mandatory arguments.

**Comment by joostkremers** [comment]
Hi, thanks for the heads-up! I was aware of the change, but I didn't realise there were uses of `define-obsolete-variable-alias` in Ebib that lacked the third argument...

The renaming of `ebib-notes-use-single-file` is announced in the News section of the manual for version 2.20, so that's what I'll add as the `when` argument.

`ebib-notes-file-symbol` was renamed much earlier, in commit b545598 from 2016, which corresponds to Ebib version 2.6. But I guess it should be safe to remove that alias altogether now.

I pushed a fix that should make Ebib compile again on Emacs 28.
