### ISSUE TITLE
Customizing ebib-notes files

### ISSUE THREAD

**Issue by Richard-CAID** [joostkremers/ebib#192]
Is it possible to have ebib search multiple org files for notes where each file has multiple note entries?

I need to include my org log files in searches. I can easily add ":Custom_id:" to my PROPERTIES drawer within logs. Doing that provides a way to quickly view correspondence log notes in the ebib entry buffer. However, I get into a situation with needing more than one org file, each with multiple entries for ebib notes. Maintaining use of a single org file to receive notes generated in ebib is not a problem. 

Can this be done and how?

**Comment by joostkremers** [comment]
Currently, that's not possible, unfortunately. There's either one single notes file, or one note per entry.

It makes sense to allow any number of notes files each with any number of notes. Perhaps I'll find some time to implement that in the next few weeks. Only question then would be where to save a note when one is created.

**Comment by Richard-CAID** [comment]
My initial thought for my own workflow is to have one named note
recipient file from which I can easily refile using org-capture in other
org files. This "note-saving-file" could also be searched for entries
such that it does not require a special exclusion from note file searches.

I experimented with your ebib-note-template and discovered I could add
headline levels and send a note deeper into a headline tree. I also
checked to see that ebib would read notes from various tree levels in a
file with multiple notes - it did. I mention this since refiling notes
with org-capture will allow me to set up my org files with multiple
notes "a la orgmode". Meaning, I can organize notes so that they can be
searched visually and with tags, etc. This way I can also group notes by
tags and export to odt, html, or latex.

**Comment by Richard-CAID** [comment]
Joost, checking back. Any progress on increasing to multiple org files for notes and which file (if only one) will receive notes?

**Comment by joostkremers** [comment]
Hi, sorry for the late reply. I haven't been able to find any time to work on this yet. I need to think about how it's best presented to the user and how to make the transition from the current system as seamless as possible.

**Comment by Richard-CAID** [comment]
I appreciate diligence and will not rush a diligent process. I was
curious as to how I would set up in the meantime so that I can
transition when an update is ready. I will wait, diligently.

I appreciate your response and candor.

Richard

**Comment by joostkremers** [comment]
So lets recap and make sure we're on the same page:

1. Currently, the user has to decide whether they want to use a single note file or use one note file per note.
2. The idea is to make this more flexible and allow multiple note files, each with one or more notes.
3. There shouldn't be any restrictions on the header level of a note. It should be possible to make it a top-level header, but also level 2, 3, etc.

If I understand you correctly, 3 is already possible. (I never tried myself, but you mentioned it works. It should work, actually, because the code that searches for a note doesn't check the header level.)

My thinking currently is this:

- Nothing should change if you use a separate file for each note. These files are named based on the entry key and they are created when the user starts a new note, which makes them difficult to integrate with the other system, in which the note files are known in advance.
- Instead of having a single notes file, the user can define a list of files. A new note is created in the first file (alternatively, Ebib could ask each time which file to use), and the user is free to move and refile notes as the need arises. Notes that are moved to a file not in the list won't be accessible anymore, however.

Does this sound like a system that would work for you? Feel free to comment and make other suggestions.

**Comment by Richard-CAID** [comment]
My observations are:

 1. There are already no restrictions on header level.
 2. That adding :Custom_id: to a pre-existing PROPERTIES drawer in an
    org file while be found when there is an ebib reference with an
    entry key matching that Custom_id. The "found" org file entry will
    be displayed from the header under which the PROPERTIES drawer is
    located and include all lower headlines. Of course, an .org file in
    which a new Custom_id is placed must be searched by ebib to identify
    the Custom_id as a note.
 3. There are no restrictions on using org-capture to refile a note
    displayed in ebib through a note window.

In regard to your diligence:

 1. I cannot comment on "separate file" notes as I have not used or
    explored them.
 2. Yes, there can be a user-define list of files for multi-note .org
    files. However, for a more robust usage of notes and ebib to access
    correspondence/phone/meeting logs which can number in the ten's of
    thousands spread over year-based, client-based, or etc.-based .org
    files, it is simpler to have a directory that contains multiple
    note-containing .org files. Both a user-defined list and a
    user-defined directory work though.
 3. As to whether new notes should all go into one file (for refiling)
    versus a prompt to choose into which file to a place a note, I see
    that both can be very useful. However, if one file is used, it
    should be user-defined. For myself, one file for new notes will work
    well since I will refile new notes under other headings/subheadings
    in other files such that directing a note to one file versus another
    will not change my need to refile it - unless directing a note to a
    file includes a method to direct it into different headings at
    different levels. I have not yet explored using ebib as a simple
    "live" call log system using multiple files each with multiple notes
    that do not need to be refiled into more detailed OrgMode logs.
    Although this use has come to mind.

I appreciate an opportunity to provide input.

**Comment by joostkremers** [comment]
My current plan is the following: add an option `ebib-notes-type` which specifies whether each note gets its own file (with file names based on the entry key) or if you have multiple notes per file. If the latter, you can define a list of files and/or directories which are searched for notes. You can then set one of these as the default file to save notes to. If you don't, you'll be asked for the file to store the note to each time you create a new one.

The default value for `ebib-notes-type` is to use a single file for each note, which means that users that currently use this method won't notice any change. Users that have set `ebib-notes-file` (i.e, who use a single file for all notes) will be prompted the first time they start the new version of Ebib, to make sure they're aware of the new options and can make the required changes to their configurations. (Or perhaps Ebib could do this, if the user agrees.)

**Comment by Richard-CAID** [comment]
Simple and seamless.

I am aware I can change the headline for notes, which is currently Year
- Author - Title. I do not know syntax for altering headline contents.
Specifically, I prefer Date (year-mo-dy) to year. Year is "%T". What is
syntax for Date? (Although, I will likely put in both Year/Date and
delete one when completing each note.)

**Comment by joostkremers** [comment]
> I am aware I can change the headline for notes, which is currently Year - Author - Title. I do not know syntax for altering headline contents. Specifically, I prefer Date (year-mo-dy) to year. Year is "%T". What is syntax for Date? (Although, I will likely put in both Year/Date and delete one when completing each note.)

`%T` is actually the directive for the entire description, which is created by the function `ebib-create-org-description`. By default, it creates a description of the form `"Author (Year): Title"`. The year part contains just the year, even if the entry has a `Date` field with a full date.

To customise it, you'd have to write a function that creates the correct description and configure the option `ebib-notes-template-specifiers` to use it for `%T` instead of `ebib-create-org-description`.

You could use the following function:

```
(defun my-ebib-create-org-description (key db)
  "Return a description for an Org mode note for KEY in DB.
The title is formed from the author(s) or editor(s) of the entry,
its year/date and its title.  Newlines are removed from the
resulting string."
  (let ((author (or (ebib-get-field-value "author" key db 'noerror 'unbraced 'xref)
                    (ebib-get-field-value "editor" key db "(No Author)" 'unbraced 'xref)))
        (year (ebib-get-year-for-display key db))
        (date (ebib-get-field-value "date" key db "" 'unbraced 'xref))
        (title (ebib-get-field-value "title" key db "(No Title)" 'unbraced 'xref)))
    (remove ?\n (format "%s (%s / %s): %s" author year date title))))
```

Which creates a description of the form `"Author (Year / Date): Title"`. To get the format "year-mo-dy" you'll have to enter the date that way in the `Date` field, but I assume you do that already.

HTH

**Comment by Richard-CAID** [comment]
I am not a programming person (yet?), but I will give this a try in the
next week or so. I appreciate your help.

**Comment by joostkremers** [comment]
You'd need to put the function above in your `init.el` file and then customise the option `ebib-notes-template-specifiers` (`M-x customize-option RET ebib-notes-template-specifiers RET`) and then change the function `ebib-create-org-description` to `my-ebib-create-org-description`:

![Screenshot from 2021-02-09 15-34-45](https://user-images.githubusercontent.com/191630/107379509-47d70780-6aed-11eb-9d20-6dd5826acba8.png)

**Comment by joostkremers** [comment]
Just wanted to let you know that I have working code now that makes it possible to use more than one file with external notes. I haven't tested it fully yet, so I'm not updating the package yet, but if you are familiar with Git and want to check it out, the code lives in the `devel` branch.

**Comment by Richard-CAID** [comment]
Great! I am bogged down with work and have not been able to work at
ebib. I have integrated it into my work regime and have a hundred or so
entries across a few .bib files to experiment. When I have a chance, I
will check out the code. Your work is much appreciated.

**Comment by Richard-CAID** [comment]
Joost,

I scrubbed and reinstalled my system. I sat down to get your new code 
but could not find "git devel branch" on git hub. Where do I find it?

**Comment by joostkremers** [comment]
I've since merged the code into the master branch, so if you installed Ebib from Melpa, it should be enough to update to the latest version. In fact, if you update your packages regularly, you may already have the new version. I tried to keep the new system backward-compatible with the old system, so existing users shouldn't notice any difference.

I've deleted the `devel` branch completely, because that workflow wasn't working for me. I'm trying out a different workflow now.

**Comment by Richard-CAID** [comment]
I seem to be having trouble with ebib-notes-location. I have set 
ebib-note-storage to "Use multiple notes per file" and have set 
ebib-notes-default-file and ebib-notes-directory. However, when I 
attempt to enter a directory for ebib-notes-location, each time I select 
INS it adds DEL but I have no opportunity to enter a directory. I have 
attached a screen shot for reference.

**Comment by Richard-CAID** [comment]
Joost,

I did not discover why org-customize was not functioning to set 
ebib-notes-locations. I use spacemacs and placed (setq 
ebib-notes-locations '("~/Documents/Library/Bib_Notes/")) into 
dotspacemacs/user-config and was able to get multiple files for multiple 
notes working... yes!! I also removed a default file from 
ebib-notes-default-file to ensure I can select where notes go.

Very much appreciated!

**Comment by joostkremers** [comment]
What you saw was the result of an incorrect description of the type of `ebib-notes-locations`. I just fixed it, so if you prefer to customise Ebib through the Customize buffer, you can do so now.

Thanks for pointing out this error. :slightly_smiling_face:
