### ISSUE TITLE
clarify multiple citation section

### ISSUE THREAD

**Issue by bdarcus** [joostkremers/ebib#195]
The docs section on multiple citations is confusing to me, in particular the second paragraph, which says this:

> This method of multiple selection is somewhat cumbersome and it does not use Emacs’ standard completion function completing-read, so it is likely unfamiliar to most users. For these reasons, it is not enabled by default, but it is there if you want to use it.

Two questions, that you might use to clarify this at some point:

1. What does the "this" refer to? The preceding paragraph describes different methods, so not clear to me. If it only applies to selectrum, etc., then you might move those last two sentences of the preceding paragraph to this one, so that it's clear that paragraph is only about that subset in particular.
2. Is this a temporary limitation you intend to fix at some point, and make default?

**Comment by joostkremers** [comment]
Yes, I can see how that could be confusing... The "this" refers to selecting multiple citations with Emacs' built-in completion mechanism. (TBH, I haven't tried out multiple selection with selectrum, perhaps it's less cumbersome.) I'll try and change the text to make it clearer and easier to understand.

It's not a temporary limitation that I intend to fix (or even could fix...) because it's how Emacs' built-in completion works. With ivy and helm, you get a list of candidates where you can mark the ones you want to select. I find that quite intuitive and easy to do. Emacs' built-in multiple completion just isn't as convenient, I think.

I also have the impression that few users are even aware that Emacs has a built-in way for completing multiple candidates, so I'm afraid that if I enable it by default, it might be confusing to users.

**Comment by bdarcus** [comment]
OK, thanks.

FWIW, I was interested in checking the status of the selectrum
ecosystem; how I stumbled on the fact that ebib now has support for
it.

**Comment by joostkremers** [comment]
> OK, thanks. FWIW, I was interested in checking the status of the selectrum ecosystem; how I stumbled on the fact that ebib now has support for it.

I switched to selectrum myself  a couple of weeks ago, so obviously I wanted to support it in Ebib. :slightly_smiling_face: 

I just noticed that selecting multiple citation keys doesn't work with Emacs' built-in completion or with selectrum, though... I'll need to fix that.

**Comment by bdarcus** [comment]
I had forgot about this discussion, but thought you might like to know that I recently put a feature request for just this issue to selectrum. It looks pretty likely we'll see a PR POC sometime soon, that you may want to contribute feedback on.

**Comment by joostkremers** [comment]
Thanks for the heads-up, I'll try and keep an eye on this.
