### ISSUE TITLE
Must ebib-entry be a temp buffer?

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#199]
It's seems to mess up some default popup-suppression/grouping rules  (in Doom emacs), sometimes when working in workspaces or in a tabbed interface (see sreenshot) etc. 

I have ebib configured like so at the moment, where the only thing relevant is `ebib-popup-entry-window` I guess (I'm not using a index-only but a split inteface) :

```
        ebib-layout 'window
        ebib-popup-entry-window nil
        ebib-window-vertical-split nil
        ebib-index-window-size 30
        ebib-bibtex-dialect 'biblatex
        ebib-autogenerate-keys nil
        ebib-use-timestamp t
```

![gnome-shell-screenshot-SW2M10](https://user-images.githubusercontent.com/68159077/114545554-6330d100-9c5c-11eb-93fe-3d24f4084566.png)

Also, thaks for updating the keybindings C-c C-c/C-c C-k... helps a lot!

**Comment by joostkremers** [comment]
Actually, `*ebib-entry*` isn't a temp buffer, it's created when Ebib is started and it's killed when you call `ebib-quit`. As long as you keep Ebib running (if only in the background) it should continue to exist.

The ear muffs indicate the Ebib buffers are internal, but perhaps I should also give them names that start with a space. That should stop them being displayed by `list-buffer` etc.

But to be honest, I'm not entirely sure what the problem is you are seeing. I don't use Doom and I also don't use tabs, so it's hard for me to figure out.

**Comment by oatmealm** [comment]
Yes, it's difficult to follow every Doom tweak... anyways, I think this may have solved the problem as far as Doom is considered. There's a list of functions that I can update to specifiy which buffers are "real". Again, Doom specific. The difference is that I don't get `*Ebib-entry*` displayed as a tab together with all the other open "non-real" buffers.... 

```
(add-hook! 'doom-real-buffer-functions
    (defun +binder-buffer-p (buf)
      (string-match-p "^\\*Binder" (buffer-name buf))))
```


![gnome-shell-screenshot-TWP110](https://user-images.githubusercontent.com/68159077/114863100-9a83b700-9def-11eb-93e7-abfccf5a7979.png)
