### ISSUE TITLE
How can I trim down the Timestamp column in index view?

### ISSUE THREAD

**Issue by svictor9** [joostkremers/ebib#207]
I'm having trouble trimming down the timestamp column in the index view. I'd like it to display only the first 10 characters but with the following setting the display looks like the attached screenshot where the timestamps have 20 chars. Am I doing something wrong ?
```
(setq ebib-index-columns '(("Author/Editor" 40 t)
			   ("Year" 4 t)
			   ("Title" 70 t)
			   ("Url" 3 t)
			   ("Timestamp" 10 t)))
```
![Screenshot_2021-07-07_14-11-29](https://user-images.githubusercontent.com/6313882/124756882-42aba680-df2d-11eb-987a-4abe6e8d52b2.png)

**Comment by joostkremers** [comment]
Actually, there's a secret feature that the last column in `ebib-index-columns` isn't actually truncated... I thought that was documented somewhere, but if it is, I can't find it now. :confused: 

The reason is that in the default setup, the last column is the title and I figured it would be OK if it takes up whatever space is left on the line.

I guess it would be best to make this more configurable. What you can do for now, however, would be to customise the option `ebib-field-transformation-functions` and add an entry for "Timestamp", then attach a function to it that truncates the timestamp field:

``` emacs-lisp
(defun my-ebib-truncate-timestamp (field key db)
  "Truncate the timestamp field."
  (substring (ebib-get-field-value field key db "" 'unbraced) 0 10))
```

This would have the added advantage that you would not get the ellipsis dots after the timestamp.

**Comment by svictor9** [comment]
> The reason is that in the default setup, the last column is the title and I figured it would be OK if it takes up whatever space is left on the line.
That makes sense of course! Maybe I should ponder following the default setup then… Actually, I only use the timestamp field for the occasional sorting.

Thanks for the solution with `ebib-field-transformation-functions` as well.
