### ISSUE TITLE
Jump to field in entry buffer

### ISSUE THREAD

**Issue by Hugo-Heagren** [joostkremers/ebib#210]
I really like being able to jump around between entries in the index buffer. It would be useful too to be able to jump between fields in the entry buffer when editting entries. I sometimes have to transcribe non-machine-readable text into bibtex entries and this would make it less tedious to move around the fields. <kbd>j</kbd> is unbound in the ebib entry map, so it could be the default there too.

**Comment by joostkremers** [comment]
Yeah, that sounds like a useful idea. Shouldn't be too difficult to implement, either, I'll put it on my to-do list. I don't have much time right now to work on Ebib, though, so I can't say when I'll get to it.

**Comment by joostkremers** [comment]
Hi, I just pushed a commit that provides this functionality. Should appear on Melpa in a few hours. Let me know if you run into any issues.

**Comment by Hugo-Heagren** [comment]
Thanks, that was fast! Just pulled this and it works perfectly for me!

As a side note, I use ivy, and I think I might experiment with adding actions to the selection menu in `ebib-jump-to-field`, reflecting the different things you can do on fields in the normal entry buffer (e.g. copy/kill the field's contents, yank from the kill-ring into the field). If this works and it seems at all useful, would it be worth my submitting a PR of what I come up with?

**Comment by joostkremers** [comment]
That's actually a pretty good idea.

I'd propose two small changes in the implementation: First, I would use the existing function names for the argument-taking functions, and use `current` in the name of the functions that operate on the current field. That sounds more logical to me. So your `ebib-copy-name-field-contents` would be `ebib-copy-field-contents`, and your `ebib-copy-field-contents` would be `ebib-copy-current-field-contents`.

Second, I'd prefer it if the ivy actions would be placed in a new file `ebib-ivy.el`, which an ivy user can then `require`.

If you'd like to make those changes, then please go ahead! 

(Ideally, BTW, all ivy-related functionality would be moved to `ebib-ivy.el`, and similarly for helm and selectrum/embark, but that will require more work, because right now the use of ivy/helm/selectrum-related functions is hard-coded in several places. They would have to be made configurable. Your change would be a good first start in that direction.)
