### ISSUE TITLE
Key choice for adding to dependant database (M a) should include more searchable information, like ebib-jump-to-entry

### ISSUE THREAD

**Issue by Hugo-Heagren** [joostkremers/ebib#214]
I very rarely remember the keys I have assigned to different entries, and I rely heavily on the fact that `ebib-jump-to-key` can search over lots of the information in an entry (especially the title and author's name). It would be good to see this in the choosing interface for `ebib-dependant-add` too.

**Comment by joostkremers** [comment]
This won't be too difficult to implement, albeit with one regression: right now, when you call `ebib-dependent-add-entry`, you can only select those keys from the main database that are not in the dependent database yet. Changing `ebib-dependent-add-entry` to use the same interface as `ebib-jump-to-entry` loses that. You'll see all the entries in the main database and there is no indication that an entry is already in the dependent.

This isn't really that bad, because the entry won't be added twice, so I'll go ahead and implement it. At a later date, I may add it back again. It's not impossible, it just takes some extra work.

**Comment by joostkremers** [comment]
This should now be implemented. Let me know if you run into any problems.

**Comment by Hugo-Heagren** [comment]
All seems to work for me, thanks!

> At a later date, I may add it back again. It's not impossible, it just takes some extra work.

Yes, I can see how this might work. I wonder if different users might want different behaviour: some people might find it confusing that some entries don't show up in the menu, or others might want them to show up but be somehow marked (with a different face, or a leading asterisk or something). Obviously this would be even _more_ work, but it might be useful for some people.
