### ISSUE TITLE
Can't push to a dependant database with a filter active

### ISSUE THREAD

**Issue by Hugo-Heagren** [joostkremers/ebib#223]
As the title. I wanted to push all entries matching a filter to a dependant database, so I filtered and then marked everything, but `ebib-dependent-add-entry` failed. I presume this is not the desired behaviour.

**Comment by joostkremers** [comment]
> As the title. I wanted to push all entries matching a filter to a dependant database, so I filtered and then marked everything, but `ebib-dependent-add-entry` failed. I presume this is not the desired behaviour.

It definitely isn't the desired behaviour, especially given the fact that `ebib-dependent-add-entry` contains code to handle marked entries... The problem lies in the fact that `ebib-dependent-add-entry` checks to see if it's in a "real" database, i.e., one that is not a dependent and not filtered. So you cannot execute the command from a filtered database.

Which, I agree, doesn't make sense. It's a very easy fix, though, which I just pushed to master. (Note, though, that the current master doesn't include your PR yet.)

**Comment by Hugo-Heagren** [comment]
> which I just pushed to master

Just tested locally and it's works perfectly! Thanks!
