### ISSUE TITLE
Preserve the original rank of bib entries

### ISSUE THREAD

**Issue by Canvis-Me** [joostkremers/ebib#234]
Hello, can you provide an option not to sort bib entries? 
Because the original bib entries ranking contains the information of ref index which is not included in bib file. So it will be better if ebib not sorts the content in such circumstances.

**Comment by joostkremers** [comment]
Unfortunately, this isn't possible. When Ebib reads a `.bib` file, it doesn't keep track of the order the entries appear in. They are saved in alphabetical order according to entry key, with entries with a `crossref` field saved first, so that cross-referencing works.

It's possible to specify a different sort order, but if the order you require cannot be obtained by sorting on some field or fields, Ebib won't be able to accommodate you. You'd have to add a custom field to your entries that specify the sort order, but that may not be practical to do.

**Comment by Canvis-Me** [comment]
Well, adding some info to ref key seems to help the job, thanks for your explanation.
