### ISSUE TITLE
Filter recently added entries

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/ebib#24]
When researching a topic I often download 10-20 papers and add them to my library. Since this papers are related, I would like to add some keywords to all of them. However, without the keywords, the only way to group them is with the aid of the timestamp field.

To this end, I have [implemented](https://gist.github.com/mardukbp/6575838) a way to filter entries that were added in the last N days. It requires a custom `ebib-timestamp-format` that includes the string `%jd`, that is, the day of the year the paper was added to the library, followed by the letter d. This way, there is no need to bother with date arithmetic.

@joostkremers I was thinking it would be great to have the possibility of pressing F + a number, passing the number to `ebib-filter-n-days`. Do you know if that is possible?

**Comment by scottmartincampbell** [comment]
This bit of code sounds great, but don't seem to work with the latest ebib (2015-01-02). Would it be hard to update it?

**Comment by joostkremers** [comment]
The code contains some function names that have changed and field names are now string. The following code fixes this (untested):

```lisp
(defun ebib-filter-n-days (n)
  "Filter entries added in the last n days"
  
  (let* ((field "timestamp")
	 (day-of-year (string-to-number (format-time-string "%j")))
	 (n-days-ago (- day-of-year (- n 1)))
	 (days-between (number-sequence n-days-ago day-of-year))
	 (regexp-days-between (mapconcat (lambda (x)
                                           (concat "\\(" (number-to-string x) "d\\)"))
                                         days-between "\\|")))
    
    (ebib-execute-when
     ((real-db)
      (ebib-db-set-filter `(contains ,field ,regexp-days-between) ebib--cur-db)
      (ebib-redisplay)))))

(defun ebib-filter-added-nth (key)
  (interactive (list (if (featurep 'xemacs)
                         (event-key last-command-event)
                       last-command-event)))
  (ebib-filter-n-days (- (if (featurep 'xemacs)
			     (char-to-int key)
			   key) 48)))

(mapc #'(lambda (key)
          (define-key ebib-filters-map (format "%d" key)
            'ebib-filter-added-nth))
      '(1 2 3 4 5 6 7 8 9))
```

**Comment by scottmartincampbell** [comment]
This new code works, but change `ebib-execute-when` to `ebib--execute-when`, and `ebib-redisplay` to `ebib--redisplay`. Thanks!

**Comment by joostkremers** [comment]
Thanks, I missed those... I created a gist with the correct code, which can be found [here](https://gist.github.com/joostkremers/de6bf299a3941b0f1129).

**Comment by scottmartincampbell** [comment]
What with the new year, I've discovered a small bug in the gist, line 9. It doesn't pad the timestamp properly with '0's. As is, it filters for timestamps like `11d` which will match `211d`. I changed `(number-to-string x)` to `(format "03d" x)`, so that the filter gets padded properly. 

Another problem is that the filter doesn't care what year it is. My simple solution is just to rewrite last year's timestamps to drop the 'days ago' component. So `timestamp = {2015-01-10 10d}` becomes `timestamp = {2015-01-10}`. I just used sed to quickly remove everything. Not perfect, but it works for now, and will have to be done again each year I suppose.

**Comment by mardukbp** [comment]
Sorry for the mess. Even though the code requires a yearly
tweak it worked for me. Now I do not need it, but I am glad
you found it useful.

**Comment by joostkremers** [comment]
I did a little experimenting and found that there's actually a better way that's general enough to be added to Ebib. I'll see about implementing it in the next few days.

**Comment by joostkremers** [comment]
I just added the command `ebib-list-recent`, which asks for a number of days and then filters the database, listing the entries added since that number of days. It requires that the `timestamp` field is in a format that can be converted into Emacs' internal time representation, but if you haven't customised the format string for the timestamp (i.e., the option `ebib-timestamp-format`), it should work.

The command uses Emacs' built-in time calculation functions, so it works fine across the new year. I haven't bound it to any key, but it's easy to do that yourself, also using the method mentioned above in this thread.

I also added a small section to the manual describing the functions used for this functionality. They exploit the fact that a filter is actually just a bit of runnable Lisp code, so they can actually contain any Lisp expression as long as it returns a boolean. The new section (called "Special filters") describes how this is done.

I haven't tested this very extensively, so let me know if you run into any trouble.

**Comment by scottmartincampbell** [comment]
Thanks! I'll test and let you know if anything comes up.

**Comment by scottmartincampbell** [comment]
One observation: there's no filter indication in the mode line, which could be confusing since several things like "save" are disabled for filtered databases. Not sure what would work, since it's not a normal filter. Even just the word "filtered" would help though.

**Comment by joostkremers** [comment]
Yes, I realised that, too, but I'm not sure how to deal with it. It's possible to simply display the Lisp expression, but since that contains the time in Emacs' internal representation, it's fairly meaningless.

For the moment, I'll just have it display `|Filtered|`, until I figure out a better way.

**Comment by scottmartincampbell** [comment]
I think `|Filtered|` is acceptable, at least until any other special filters are created. Thanks!

I'd say this issue can be closed again.

**Comment by joostkremers** [comment]
I'll close it and create a new issue for the mode line indicator so it doesn't get lost.
