### ISSUE TITLE
`literal` in `rx` not supported in Emacs 26

### ISSUE THREAD

**Issue by joostkremers** [joostkremers/ebib#249]
The `literal` construct was introduced in Emacs 27, but Emacs still officially supports Emacs 25.

@Hugo-Heagren, may I assume you introduced the relevant code? :slightly_smiling_face:

https://github.com/joostkremers/ebib/blob/600b5e3d3dd98ba4017ad257470424b4507b4e59/ebib.el#L260

The documentation says that `literal` evaluates its argument and includes the result of evaluation into the regex. In this case, however, the argument of `literal` is always a string, so there doesn't seem to be any need for evaluation, right? I think we can change the code:

    (rx line-start (literal string) (syntax -))
    
to:

    (rx line-start string (syntax -))
    
What do you think?

**Comment by Hugo-Heagren** [comment]
> In this case, however, the argument of `literal` is always a string,
> so there doesn't seem to be any need for evaluation, right?

You're right that the argument is always a string, but it I think it
still needs to be evaluated. rx.el works by interpreting a dsl of
symbols like `line-start`, `syntax`, etc. Everything listed in the rx
documentation is a symbol. Incidentally, this is why `rx` (the lisp
form) is a macro -- if it wasn't, you'd have to write `(rx 'line-start
'(syntax -) 'etc...)`, quoting each argument to make it a symbol.

Thus, by default `rx` doesn't evaluate its arguments. Try your
suggested code, then `C-x C-e` after it. You should get an error
`(error "Unknown rx symbol ‘string’")`, because `rx` is trying to
interpret the symbol `string` as one of its constructs (and failing
-- there is no `string` construct).

Instead, we need to force `rx` to evaluate `string` (the symbol) to
get the value of the variable, and this is what the `literal`
construct does.

**But** of course you're right that this isn't satisfactory, because
`literal` isn't available in some recent versions of Emacs.

## Solution
The variable has to be evaluated at call-time, because it's only *set*
at call time (unlike something like a custom option, which might be
set when the function is defined).

This means that we *can't* use `eval` in `rx`, because `eval` forms
are expanded at macro-expansion time for `rx`. However, `rx-to-string`
is a function, which takes an rx sexp form as a list. We could just
use a backquote and a comma to include the variable in the list
directly, like this: 

``` emacs-lisp
(defun ebib--redisplay-strings-buffer ()
  "Redisplay all strings in strings buffer."
  (with-current-ebib-buffer 'strings
    (let ((inhibit-read-only t)
          (string (ebib--current-string)))
      (erase-buffer)
      (ebib--fill-strings-buffer)
      (re-search-forward
       (rx-to-string `(: line-start ,string (syntax -)) t)))))f
```

The backquote construct is evaluated at call-time, so this works. I'll make PR.

**Comment by joostkremers** [comment]
> You're right that the argument is always a string, but it I think it still needs to be evaluated.

Yes, the *symbol* needs to be evaluated, to produce the string. I thought that would happen as part of the function call, but `rx` is a macro, as you say, so that's not actually true.

> Thus, by default `rx` doesn't evaluate its arguments. Try your suggested code,

Yes, I tried it after I posted the suggestion and found out I was wrong.

> `rx-to-string` is a function, which takes an rx sexp form as a list. We could just use a backquote and a comma to include the variable in the list directly

I thought about using `regex` instead of `literal`, and wrapping `string` in a call to `regexp-quote`, but this works too, of course.

> I'll make PR.

Thanks.
