### ISSUE TITLE
Cannot create file name from temporary key when using ebib-import-file

### ISSUE THREAD

**Issue by nicodebo** [joostkremers/ebib#252]
Hello,
I have this function that allows me create an entry with some pre written fields:
```elisp
(defun nd/ebib-add-bulletin ()
  (interactive)
  (ebib--add-entry-stub (list (cons "=type=" "Misc")
                              (cons "author" "aaa")
                              (cons "title" "doc YYYY-MM")
                              (cons "date" "YYYY-MM-DD")
                              (cons "organization" "aaa")))
  (ebib--update-buffers))
```
1. call nd/ebib-add-bulletin function
2. edit the date field and save the database
3. call ebib-import-file which generate an error: 'Cannot create file name from temporary key'

Do you know how can the temporary key be turn into a «real» one ? From the documentation it is stated that editing the entry should replace the temporary key but it's not working in my case.

**Comment by joostkremers** [comment]
> I was doing `ebib-save-current-database` without never doing `ebib-quit-entry-buffer`. Now it's working perfectly. Thank you.

It's a bit unfortunate that Ebib is sometimes very dependent on the right buffer being selected during certain operations. This, I'm afraid, is one such case. The alternative would be to recreate the key every time a field value is changed, which I think would be problematic, because most of the time you don't *want* the key to change. That would only lead to existing documents not compiling anymore because the BibTeX keys of the entries changed in the `.bib` file.

Anyway, I'm glad it's working for you now. If you have any suggestions for improving Ebib so it matches your workflow better, feel free to let me know.
