### ISSUE TITLE
ebib: add support for multiple entries using vertico

### ISSUE THREAD

**Issue by atanasj** [joostkremers/ebib#262]
Not sure if this is currently possible, but adding support for this with `vertico` would be great!

See: https://github.com/emacs-citar/citar/pull/163 for something similar.

**Comment by joostkremers** [comment]
Hi, have you tried setting `ebib-citation-insert-multiple` to `t`? I'm using selectrum at the moment, though considering trying out vertico. Since vertico is closely integrated into the default completion mechanism, from what I understand, setting this option may already get you a good part of the way there.
