### ISSUE TITLE
Link to ebib entry in org mode

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/ebib#27]
Following a great suggestion from ebib's manual I came up with a function to automate the process of creating a link to an entry in ebib from my notes file in org-mode.

``` Scheme
(org-add-link-type "ebib" 'ebib)
(defun org-ebib-link ()
  (interactive)

  (let* ((collection (edb-keys-list ebib-cur-db))
     (org-ebib-key (completing-read "Select key: " collection)))
    (insert "[[ebib:" (format "%s" org-ebib-key) "][" org-ebib-key "]]")))
```

**Comment by jb-stack** [comment]
> Ebib actually comes with a command to do this: `ebib-insert-bibtex-key`. You still need to add
> 
> ```lisp
> (org-add-link-type "ebib" 'ebib)
> ```
> 
> to your `.emacs`, but then it should work.

This doesn't work for me. `ebib`'s signature expects KEY as its second argument, while also accepting an optional FILE as its first argument:

```lisp
(ebib &optional FILE KEY)
```

On the other hand, `org-add-link-type` has the following signature:
```lisp
(org-add-link-type TYPE &optional FOLLOW EXPORT)
```
and the following notes from the documentation:

> FOLLOW should take the link path as the single argument and do whatever is necessary to follow the link, for example find a file or display a mail message.

Accordingly, passing `'ebib` as the `FOLLOW` argument results in the key being passed as the `FILE` argument to `ebib` and ebib then attempts to open a database file with that name instead of finding the key in the currently open database. My fix was to wrap it in a function which passes the key as the second argument instead:

```lisp
(defun my-ebib (key)
   (ebib nil key))
(org-add-link-type "ebib" 'my-ebib)
```

**Comment by joostkremers** [comment]
That's because the advice given above is no longer valid. It should now be enough to do `(require 'org-ebib)` in your init file. That should also make `org-store-link` work properly.

Do let me know if you run into problem, though.
