### ISSUE TITLE
`ebib-index-default-sort` doesn't respect local setting?

### ISSUE THREAD

**Issue by Hugo-Heagren** [joostkremers/ebib#304]
I want to set `ebib-index-default-sort` locally in a directory. I have the following:

``` elisp
((nil . ((ebib-index-default-sort . ("date" . descend))
	 (ebib-preload-bib-files . ("~/CV/cv.bib")))))
```

The second assignment works as expected. If I open another file in the directory, and then open ebib, ebib opens with cv.bib loaded. But it sorts it with the global value of `ebib-index-default-sort`, not with the local value. If I open another file in the same directory and inspect the value, the local value is shown. So I think ebib is failing to respect the local value of the variable.

What's wrong?

**Comment by joostkremers** [comment]
> What's wrong?

Probably what's happening is that when `ebib-index-default-sort` is accessed, the buffer that's current isn't visiting a file (either in that specific directory or at all), so that the directory-local variables are ignored. (Directory-local variables are essentially just file-local variables, so they only apply to buffers that are visiting a file.)

`ebib-preload-bib-files` is accessed when Ebib is initialised, at a point where the windows/buffers haven't been set up yet. Given that you first open some other file in the relevant directory and then start Ebib, Ebib sees the directory-local value of `ebib-preload-bib-files`, because the file-visiting buffer is still active.

`ebib-index-default-sort`, on the other hand, is (usually?) accessed when Ebib's index buffer is active. Since that buffer is not visiting a file, directory-local variables do not have any effect.

I'm not sure what could be done to change this, but I suspect it would take some work...

**Comment by joostkremers** [comment]
Reading the Elisp manual section on dir-local variables, I noticed there is a function `hack-dir-local-variables-non-file-buffer`, which can be used to set dir-local variables in a non-file-visiting buffer. We could call that in the index buffer early in the initialisation process. To what extent that would solve the problem, I don't know, but it would be a first step.

It would probably also have to be done in the entry and strings buffers, BTW.
