### ISSUE TITLE
Multiple files: show filename not just number?

### ISSUE THREAD

**Issue by rdiaz02** [joostkremers/ebib#311]
I often have multiple files in an entry (main paper, suppl. mat., etc). When I press "f", and as per the documentation, "It is also possible to have more than one filename in a field. In that case, Ebib asks you which one you want to open." However, I am given 

```
Select file [1-3]: 
```

Is there an easy way to show the actual filenames?  (I've read over https://github.com/joostkremers/ebib/pull/235 but I am not sure the solution is there).

**Comment by joostkremers** [comment]
> Is there an easy way to show the actual filenames?

Currently, no, because the behaviour you describe is hard-coded. I agree that it would be much nicer to show the file names, and it shouldn't be difficult to change that. I'll try to find some time.

>  (I've read over #235 but I am not sure the solution is there).

No, that's about editing the field value, not about selecting a file to view.

**Comment by joostkremers** [comment]
I pushed a commit that should fix this: you can still type `M-2 f` to open the second file (which was the reason behind using a number to select the file), but if you just hit `f`, you are now asked the file name with completion. Note that this is not the standard file-name completion, because that would offer the files on disk as completion candidates. Instead, it uses string completion, but it should do what you want. Let me know when you run into issues.

**Comment by rdiaz02** [comment]
Just tried it quickly with a variety of entries with differing numbers of attached files (1 to 16), and with files of different kinds (pdf, html, png, zip). It works perfectly!! Thanks! I guess we can close the issue (I'll reopen if I run into issues).
