### ISSUE TITLE
BibTeX entry with empty field

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/ebib#59]
Some BibTeX citations downloaded from journals include an empty field such as 

```
year = "1967",
eid = ,
pages = "962-982",
```

After importing to ebib, the `.bib` file reads 

```
year = "1967",
eid = pages = "962-982",
```

which results in an error when running BibTeX.

**Comment by joostkremers** [comment]
I've pushed a fix for this to `parsebib.el` (the library that Ebib now uses for reading `.bib` files). I tried loading an entry with an empty `eid` field formatted as you mention, and it works alright. The field is given an empty value. Note that since `eid` is among the standard hidden fields, it won't be shown by default. Type `H` to see it, or remove it from the user option `ebib-hidden-fields`.

**Comment by mardukbp** [comment]
Thank you!
