### ISSUE TITLE
Maintain order #42/#55 again...

### ISSUE THREAD

**Issue by duerrp** [joostkremers/ebib#62]
Hi Joost,

Unfortunately the bug is back. I recently updated ebib and with the current version (20150107) the order of the fields in the entries is shuffled after saving. Moreover, every time I save, a pair of newlines is added around the `ebib--bibtex-dialect: BibTeX` line.

Sorry for the trouble
Peter

**Comment by joostkremers** [comment]
Hi Peter,

Don't be sorry, I'm the one that should apologise. I should check more carefully that saving a `.bib` file doesn't change anything that the user didn't change.

I can reproduce the bug with the `@Comment` string. I just pushed a fix for that. Note, BTW, that you can delete the `@Comment` with the `ebib--bibtex-dialect` line in it (and also an `@Comment` with `ebib-bibtex-dialect`, if you have one). The BibTeX dialect is now stored in a local variable block at the end of the file.

The other problem now occurs when reading a `.bib` file, not when saving it. So it had to be fixed in `parsebib.el` (a new dependency of Ebib, which will have been installed automatically when you updated Ebib). I pushed a fix for it as well.

**Comment by joostkremers** [comment]
I'll try and be a bit more careful next time with changes of this kind. I never kept my `.bib` files under revision control, but I just created a repo for them so I can keep track of things. Hopefully it's the last time you encounter this bug!

**Comment by duerrp** [comment]
Hi Joost,

Thank you so much. The current version works perfectly!

**Comment by joostkremers** [comment]
Putting my `.bib` file in version control turned out to be a good idea. I noticed that there was a similar problem with the `@String` definitions. I guess you don't use those, otherwise you would have noticed before. :-)

Thanks for reporting the issue and for your patience. Like I said, I'll do my best to make this the last time you've had to complain about it.
