### ISSUE TITLE
Fields with newline cause display bug if included in index buffer

### ISSUE THREAD

**Issue by scottmartincampbell** [joostkremers/ebib#63]
Hi Joost,

Using ebib-20150119.144 (and the previous version) I noticed that if a title field has a newline (I used bibtex-mode to clean an entry outside of ebib) and I include titles in the index buffer, ebib includes the newline and it throws off the indexing when scrolling through the entries. The entry buffer just treats the field as a multiline field, so no data is lost as far as I can tell, but the index buffer is confused.

It looks like a fix is needed in ebib--display-entry-key. Maybe a helper function to replace "\n[whitespace]" with a single space " " before adding fields to the entry buffer? 

Along these lines, just as a point of discussion,  it would be great if it were possible to reveal multiline fields in the entry buffer, to read my notes without having to actually open them in the multiline buffer. Something like ebib-toggle-hidden.

**Comment by joostkremers** [comment]
Hi Scott,

Thanks for reporting this issue. It should be fixed in commit 261a602. The necessary helper function already exists, so that was a quick fix. :-)

As for viewing the contents of multiline fields, I understand what you mean. There is the function `ebib-show-annotation` (bound to `A` in the index buffer), which displays the contents of the `annotation` (or `annote`) field in a `*Help*` buffer. But it only works for the one field, of course. It shouldn’t be too difficult to write a function that does something similar in the entry buffer.

I’ll see what I can come up with.

**Comment by joostkremers** [comment]
Ok, the latest commit provides a function `ebib-view-field-as-help`, which shows the contents of the current field in a `*Help*` buffer. The buffer is selected and can be dismissed again with `q`. This may still not be ideal (you can only see one multiline field at a time) but it's better than nothing.

**Comment by scottmartincampbell** [comment]
The new function `ebib-view-field-as-help` works great, thanks!

However, I can't see additional fields in the index buffer anymore, just the entry key.

**Comment by joostkremers** [comment]
Sorry, I messed up... Should be fixed in the latest commit.

**Comment by scottmartincampbell** [comment]
Thanks! 

I've really enjoyed getting into ebib over the last few weeks and learning how you made it work. Changed my entire workflow, for the better.
