### ISSUE TITLE
Bad or corrupted data in the .bib file.

### ISSUE THREAD

**Issue by scottmartincampbell** [joostkremers/ebib#65]
Hi Joost,

I've come across a couple of issues relating to the database saving bad or corrupted data to the .bib file. 

1. This first one is a parsing issue when putting bad data in an entry. If there's an unbalanced brace in the field, the data gets saved, but then the file can't be parsed and re-opened. Easy to reproduce: just put "{" or "}" in a field. 

That said, it's up to the user to not use unbalanced braces in a field, but I found out the hard way when I copied a brace into a field by mistake. It's easy to fix by hand, but maybe a warning before saving would be helpful? As a bonus, it would be great if ebib detected some special LaTeX characters, like $ or % before saving, but now I'm just getting selfish.

2. This one is a bit more complicated and serious. To reproduce: in a database with at least two entries, open a multiline buffer. Put an org-mode style link to different entry, ie: [[ebib:entrykey]]. Follow that link (`org-open-at-point`). Go back to the multiline buffer and quit or save. The type of the first entry is now set to the org-mode link, and if the db is saved, the .bib is corrupted. Actually, following an org-mode file link (eg: [[file:~/test.txt]]) will do the same. 

Again, found this one the hard way. Not sure where the problem lies. 

Sorry to be a bother. I really am enjoying using ebib, and I just ran into these problems while testing ways to incorporate it into my workflow.

**Comment by joostkremers** [comment]
Hi Scott,

> This first one is a parsing issue when putting bad data in an entry. If there's an unbalanced brace in the field, the data gets saved, but then the file can't be parsed and re-opened. Easy to reproduce: just put "{" or "}" in a field.

Yeah, that’s not surprising. Ebib uses braces as field delimiters, so when you use unbalanced braces in a field value, the parser will get confused. I suspect that such files can’t be handled by BibTeX either (though I haven’t tested.)

BibTeX offers a solution by enclosing field values in double quotes. However, switching to double quotes all around won't be very helpful, because then you can’t use double quotes in field values.

I agree something should be done to fix this. Either a warning or perhaps it’s possible to choose the field delimiters based on the contents of the field. I’ll have to think about it a bit.

> As a bonus, it would be great if ebib detected some special LaTeX characters, like $ or % before saving, but now I'm just getting selfish.

What exactly would you want to do with those? Escape them? That should be possible.

> This one is a bit more complicated and serious. To reproduce: in a database with at least two entries, open a multiline buffer. Put an org-mode style link to different entry, ie: [[ebib:entrykey]]. Follow that link (org-open-at-point). Go back to the multiline buffer and quit or save. The type of the first entry is now set to the org-mode link, and if the db is saved, the .bib is corrupted. Actually, following an org-mode file link (eg: [[file:~/test.txt]]) will do the same.

Essentially the problem is that the multiline edit buffer doesn’t know to what field of what entry it belongs. It is just a buffer with some text, and when you save the text, Ebib must figure out which field to store it in. So far, I’ve assumed that this is simple: Ebib keeps track of the current entry and field and stores the text in whatever entry/field is current at the moment you store the text in the multiline edit buffer.

However, when you jump out of the multiline edit buffer and then return to Ebib (when following the org-mode `ebib` link, this happens immediately, when following the file link, this happens when you do `M-x ebib`), the current entry is reset.

If you then manually move back to the multiline edit field (with `switch-to-buffer` or some other Emacs function), Ebib doesn’t change the current entry back to the entry to which the text belongs. Saving the text in the multiline edit buffer then saves to the wrong entry (and field).

I think the best solution here would be to create a local variable in the multiline edit buffer that keeps track of which entry & field the text belongs to and use that info when storing the text. Shouldn’t be all that hard.

**Comment by joostkremers** [comment]
Ok, the second issue should now be fixed. Let me know if you run into any problems.

**Comment by scottmartincampbell** [comment]
Thanks for the explanation and quick fix!

Regarding the first issue and the special LaTeX characters, escaping them would be great, but as I said before, it's easy to correct these by hand. 

I tested the second issue. It definitely doesn't lead to corrupted fields anymore. 

However, one thing I noticed when testing it is that if a multiline edit buffer is open, and I jump to the ebib index and open a _different_ entry and open a _second_ multiline edit buffer, then the first multline edit buffer seems to be erased, or maybe overwritten with the second and anything in the first multiline buffer that hasn't been saved is gone. 

A warning or option to save the first buffer before that happens would be great, because I can be forgetful while taking notes and doing differeting things and forget to save the multiline buffer. Or even better, the ability to have many multiline edit buffers open at the same time would be great.

**Comment by joostkremers** [comment]
Yes, there's only one multiline edit buffer that gets reused every time. Having more than one shouldn't be too difficult. I'll let you know when I cook something up.

**Comment by joostkremers** [comment]
Hi Scott,

I just uploaded a branch `mmulti` (note the double m) that adds the ability to have multiple multiline edit buffers. In case you’re still interested, I’d appreciate it if you could test it and report any issues you find.

With this branch, when you edit a field as multiline, a new buffer is created with the major mode specified in `ebib-multiline-major-mode`. The name of the buffer specifies the entry and field. (Internally, Ebib also keeps track of which database the entry is from, so editing the same field in two identically named entries in two databases is possible). If the field you want to edit already has a multiline edit buffer associated with it, Ebib switches to it instead of creating a new one. There are checks to make sure you don’t accidentally lose data when closing a database or quitting Ebib.

I haven’t been able to test the patch thoroughly, though, so expect some issues. I’ll try to fix those as quickly as I can.

**Comment by scottmartincampbell** [comment]
I've tested the mmulti branch a little, but mostly by necessity: I think there may be a bug in the current melpa release version: 20150215.257. It wasn't closing multiline buffers properly, so it was impossible to open a new one. I tried the new branch, which is working so far, but I haven't pushed it much. 

Thanks!

**Comment by joostkremers** [comment]
Let me know if you run into problems. I haven't been able to reproduce your problem with closing the multiline edit buffer, so I have to leave that open for now. If you notice any left-over buffers in the `mmulti` branch, do let me know too, because that would be a bug that needs fixing.

**Comment by scottmartincampbell** [comment]
I haven't had any bugs. I do have a related question though. 

Before the mmulti changes, it was possible to use org-mode in the multiline buffer. Now, if I switch to org-mode (and switch back to multiline mode), any changes to the mutliline buffer are lost when I try to save them or quit the buffer.

Orgstruct as a minor mode is an okay compromise, but I liked using the full org-mode because I could use it to highlight and markup certain text (bold, italics, etc) in my notes. 

Is there a way to restore this functionality? I'd be open to a suggestion for an alternate way to get compatible markup.

**Comment by joostkremers** [comment]
Not sure I understand the problem... `ebib-multiline-mode` is still defined as a minor mode, so it should still be possible to set the major mode of multiline edit buffers to whatever you want. Personally, I use `markdown-mode` in my multiline edit buffers and that seems to work just fine.

**Comment by joostkremers** [comment]
If you change major modes, all buffer-local variables are killed. Since `ebib-multiline-mode` keeps track of which entry & field with a buffer-local variable, it makes sense that Ebib cannot store the value once you change major modes in a multiline edit buffer.

You should probably configure `ebib-multiline-major-mode` to `org-mode`, if you haven't done so already.

**Comment by scottmartincampbell** [comment]
Right. That fixed it. I missed that in the documentation. Thanks!

**Comment by joostkremers** [comment]
Perhaps I should add a note about this in the section "Editing multiline values", that should make it a bit more conspicuous.
