### ISSUE TITLE
Open file in PDF-view-mode

### ISSUE THREAD

**Issue by Enrico68** [joostkremers/ebib#68]
Hello,

I would like to use the integrated [PDF-tools](https://github.com/politza/pdf-tools) for opening the paper. Is there a way to customise it ?

**Comment by joostkremers** [comment]
Currently, Ebib opens a pdf file with the (external) viewer defined in `ebib-file-associations`, or if no association is found, it simply uses `find-file` to open the file in Emacs. So what you'd have to do is remove the association for pdf files in that variable (you can use the Customize interface to do so) and then configure Emacs to open pdf files using pdf-tools instead of the built-in docview mode. I don't know how that's done, though.

**Comment by Enrico68** [comment]
Thanks , I forgot it...!
