### ISSUE TITLE
Cannot add "month" field.

### ISSUE THREAD

**Issue by brabalan** [joostkremers/ebib#74]
Hello,

I have the following entry (as displayed in the Ebib-entry buffer):

```
type                InProceedings

author              Genev{\`e}s, Pierre and Schmitt, Alan
title               Expressive Logical Combinators For Free
year                2015
date                
booktitle           Proceedings of International Joint Conference on Artificial Intelligence (IJCAI'15)

editor              
volume              
series              
number              
note                to appear
organization        
publisher           
pages               
pubstate            
doi                 
url                 

crossref            
annotation          
abstract            
keywords            
file                

Alan                1
hal                 https://hal.inria.fr/hal-00868724v4/
```

I want to add a `month` field. As it's not present, I try to add it, but I get an error:
```
Debugger entered--Lisp error: (error "Field already exists in entry `GenevesSchmitt2015'")
  signal(error ("Field already exists in entry `GenevesSchmitt2015'"))
  error("Field already exists in entry `%s'" "GenevesSchmitt2015")
  ebib-add-field("month")
  call-interactively(ebib-add-field nil nil)
  command-execute(ebib-add-field)
```

I looked at the bib entry and there is no `month` field. How can I set it?

**Comment by joostkremers** [comment]
`month` is one of the predefined fields for the `InProceedings` entry type. So you can’t add it because it’s already there. It’s not visible, though, because it’s one of the so-called hidden fields. Type `H` in the index buffer to make these visible.

BibLaTeX defines quite a large number of fields and it’s impractical to display them all in the entry buffer. That’s why most of them are hidden by default. You can customise the fields that you want to be hidden with the option “Hidden Fields” (`ebib-hidden-fields`). See the section [Hidden fields] (http://joostkremers.github.io/ebib/ebib-manual.html#hidden-fields) in the manual for details.

I admit it would be better to have Ebib display a helpful message when you try to add a field that already exists but is hidden. I'll fix that when I get a chance.

**Comment by brabalan** [comment]
Thank you, this worked.
