### ISSUE TITLE
Request: Ebib support of biblatex "xref" or "related" fields

### ISSUE THREAD

**Issue by scottmartincampbell** [joostkremers/ebib#81]
Ebib does a great job with crossref fields. It would be great if it could also handle biblatex "xref" or "related" fields, to be able to select and follow other entry keys as with crossref. In practice, I'd think this would be simpler than crossref, since xref and related don't inherit data, and as far as I can tell, neither require special treatment with respect to sorting or key generation. 

It's just a small edge case for me and perhaps these fields are rarely used by other people, but I ran across the problem this morning for a special bib file I was creating and thought I'd ask. From the code it looks like a small handful of functions scattered in ebib.el would need changing to accommodate special fields.

**Comment by joostkremers** [comment]
Yes, I agree that would be a nice thing to have. I implemented the basic functionality, i.e., the xref and related fields now have completion and display their contents in red when they contain a key that is not in the database.

As for sorting the entries in the .bib file, I'm not sure biblatex even requires that for the crossref field. There doesn't seem to be anything about it in the manual, so I suspect it's a BibTeX thing. And even if it does, users can simply set `ebib-save-xrefs-first`.

Let me know if you run into any problems.

For completeness' sake, I'd also have to add similar functionality for the xdata field (which would be a bit more work because it can hold more than one entry key) and perhaps I should add functions for jumping to the entries referenced in the xref and related fields. Though OTOH that might be overdoing it...

In any case I'll leave this issue open for the moment, in case I find some time.

**Comment by scottmartincampbell** [comment]
That's fast! Works great.

I copied ebib-follow-crossref over to my .emacs and modified it to work
with "related" so I'm quite happy. The only trouble was overriding the
"R" reload database key. 

Thanks!
