### ISSUE TITLE
advice-add error

### ISSUE THREAD

**Issue by dowcet** [joostkremers/ebib#86]
I have just installed ebib via MELPA and  I'm running Emacs 24.3. When I try to run it I get the following message: 

`ebib--init: Symbol's function definition is void: advice-add`.

**Comment by joostkremers** [comment]
Yes, `advice-add` is more recent than Emacs 24.3. Not sure how I missed that...

I added a simple fix that should allow you to use Ebib. It disables the functionality that `advice-add` is used for, but that's a tiny matter anyway: it ensures that you return to Ebib after reading an Ebib help page in Info. Instead, you'll be returned to the window(s) you had active before you started Ebib. That should not be a big deal, because you can just call Ebib again.

Let me know if you run into any other issues.
